const learningPath = [
  {

];

const foundationalPath = [
  // --- PART 1: MATHEMATICS FOR AI/ML (Days 1-30) ---
  { day: 1, phase: "Math", topic: "Vectors Basics", subtopics: [{title: "Vector addition & Scalar multiplication", url: "https://www.3blue1brown.com/topics/linear-algebra", difficulty: "easy", type: "theory"}] },
  { day: 2, phase: "Math", topic: "Dot & Cross Products", subtopics: [{title: "Geometric interpretation & Projections", url: "https://www.youtube.com/results?search_query=Dot+product+3blue1brown", difficulty: "medium", type: "theory"}] },
  { day: 3, phase: "Math", topic: "Matrices Basics", subtopics: [{title: "Matrix multiplication & Linear transformations", url: "https://www.youtube.com/results?search_query=Matrix+multiplication+linear+transformation", difficulty: "medium", type: "theory"}] },
  { day: 4, phase: "Math", topic: "Determinants & Inverses", subtopics: [{title: "Identity matrix, Singular matrices", url: "https://www.youtube.com/results?search_query=Determinant+of+a+matrix", difficulty: "medium", type: "theory"}] },
  { day: 5, phase: "Math", topic: "System of Linear Equations", subtopics: [{title: "Gaussian elimination", url: "https://www.youtube.com/results?search_query=Gaussian+elimination", difficulty: "hard", type: "practice"}] },
  { day: 6, phase: "Math", topic: "Eigenvalues & Eigenvectors", subtopics: [{title: "Concept & Calculation", url: "https://www.youtube.com/results?search_query=Eigenvectors+and+eigenvalues", difficulty: "hard", type: "theory"}] },
  { day: 7, phase: "Math", topic: "Principal Component Analysis (PCA)", subtopics: [{title: "Dimensionality reduction math", url: "https://www.youtube.com/results?search_query=PCA+mathematics", difficulty: "hard", type: "theory"}] },
  { day: 8, phase: "Math", topic: "Derivatives Basics", subtopics: [{title: "Power rule, Product rule, Quotient rule", url: "https://www.3blue1brown.com/topics/calculus", difficulty: "easy", type: "theory"}] },
  { day: 9, phase: "Math", topic: "The Chain Rule", subtopics: [{title: "Function composition derivatives", url: "https://www.youtube.com/results?search_query=Chain+rule+calculus", difficulty: "medium", type: "practice"}] },
  { day: 10, phase: "Math", topic: "Partial Derivatives", subtopics: [{title: "Multivariable calculus intro", url: "https://www.youtube.com/results?search_query=Partial+derivatives", difficulty: "medium", type: "theory"}] },
  { day: 11, phase: "Math", topic: "Gradients", subtopics: [{title: "Gradient vectors & Direction of steepest ascent", url: "https://www.youtube.com/results?search_query=Gradient+vector", difficulty: "hard", type: "theory"}] },
  { day: 12, phase: "Math", topic: "Gradient Descent Math", subtopics: [{title: "Step size & updating weights mathematically", url: "https://www.youtube.com/results?search_query=Gradient+descent+mathematics", difficulty: "hard", type: "practice"}] },
  { day: 13, phase: "Math", topic: "Jacobian & Hessian Matrices", subtopics: [{title: "Second-order derivatives in ML", url: "https://www.youtube.com/results?search_query=Hessian+matrix+machine+learning", difficulty: "hard", type: "theory"}] },
  { day: 14, phase: "Math", topic: "Backpropagation Math", subtopics: [{title: "Chain rule applied to Neural Networks", url: "https://www.youtube.com/results?search_query=Backpropagation+calculus", difficulty: "hard", type: "theory"}] },
  { day: 15, phase: "Math", topic: "Descriptive Statistics", subtopics: [{title: "Mean, Median, Mode, Variance, Std Dev", url: "https://www.youtube.com/results?search_query=Descriptive+statistics", difficulty: "easy", type: "theory"}] },
  { day: 16, phase: "Math", topic: "Probability Basics", subtopics: [{title: "Independent vs Dependent events", url: "https://www.youtube.com/results?search_query=Probability+basics", difficulty: "easy", type: "theory"}] },
  { day: 17, phase: "Math", topic: "Conditional Probability", subtopics: [{title: "P(A|B) calculations", url: "https://www.youtube.com/results?search_query=Conditional+probability", difficulty: "medium", type: "practice"}] },
  { day: 18, phase: "Math", topic: "Bayes' Theorem", subtopics: [{title: "Prior, Posterior, Likelihood", url: "https://www.youtube.com/results?search_query=Bayes+theorem", difficulty: "medium", type: "theory"}] },
  { day: 19, phase: "Math", topic: "Naive Bayes Math", subtopics: [{title: "Applying Bayes to classification", url: "https://www.youtube.com/results?search_query=Naive+Bayes+math", difficulty: "medium", type: "practice"}] },
  { day: 20, phase: "Math", topic: "Probability Distributions", subtopics: [{title: "Normal, Binomial, Poisson", url: "https://www.youtube.com/results?search_query=Probability+distributions", difficulty: "medium", type: "theory"}] },
  { day: 21, phase: "Math", topic: "PDFs & CDFs", subtopics: [{title: "Probability Density Functions", url: "https://www.youtube.com/results?search_query=PDF+vs+CDF", difficulty: "hard", type: "theory"}] },
  { day: 22, phase: "Math", topic: "Expected Value & Covariance", subtopics: [{title: "Correlation vs Covariance", url: "https://www.youtube.com/results?search_query=Covariance+and+correlation", difficulty: "medium", type: "theory"}] },
  { day: 23, phase: "Math", topic: "Hypothesis Testing", subtopics: [{title: "Null hypothesis, p-values", url: "https://www.youtube.com/results?search_query=Hypothesis+testing+p+value", difficulty: "hard", type: "theory"}] },
  { day: 24, phase: "Math", topic: "A/B Testing Math", subtopics: [{title: "Statistical significance", url: "https://www.youtube.com/results?search_query=A%2FB+testing+statistics", difficulty: "medium", type: "practice"}] },
  { day: 25, phase: "Math", topic: "NumPy Linear Algebra", subtopics: [{title: "np.dot, np.linalg.inv", url: "https://numpy.org/doc/stable/reference/routines.linalg.html", difficulty: "medium", type: "practice"}] },
  { day: 26, phase: "Math", topic: "Coding Gradient Descent", subtopics: [{title: "Implement GD from scratch in Python", url: "https://github.com/", difficulty: "hard", type: "project"}] },
  { day: 27, phase: "Math", topic: "Information Theory", subtopics: [{title: "Entropy & Cross-Entropy Loss", url: "https://www.youtube.com/results?search_query=Cross+entropy+loss+math", difficulty: "hard", type: "theory"}] },
  { day: 28, phase: "Math", topic: "Activation Functions Math", subtopics: [{title: "Sigmoid & Softmax equations", url: "https://www.youtube.com/results?search_query=Softmax+function+math", difficulty: "medium", type: "theory"}] },
  { day: 29, phase: "Math", topic: "Optimization Algorithms", subtopics: [{title: "Adam, RMSprop Math", url: "https://www.youtube.com/results?search_query=Adam+optimizer+math", difficulty: "hard", type: "theory"}] },
  { day: 30, phase: "Math", topic: "Final Math Review", subtopics: [{title: "Connect Math to ML Models", url: "https://github.com/", difficulty: "medium", type: "theory"}] },

  // --- PART 2: DATA STRUCTURES & ALGORITHMS (Days 31-90) ---
  { day: 31, phase: "DSA", topic: "Time & Space Complexity", subtopics: [{title: "Big O, Omega, Theta", url: "https://www.youtube.com/results?search_query=Big+O+notation", difficulty: "easy", type: "theory"}] },
  { day: 32, phase: "DSA", topic: "Arrays Deep Dive", subtopics: [{title: "Memory allocation & dynamic arrays", url: "https://www.youtube.com/results?search_query=Dynamic+arrays+memory", difficulty: "easy", type: "theory"}] },
  { day: 33, phase: "DSA", topic: "Two Pointers Pattern", subtopics: [{title: "Opposite ends & Same direction", url: "https://leetcode.com/tag/two-pointers/", difficulty: "medium", type: "practice"}] },
  { day: 34, phase: "DSA", topic: "Sliding Window Pattern", subtopics: [{title: "Fixed vs Dynamic windows", url: "https://leetcode.com/tag/sliding-window/", difficulty: "medium", type: "practice"}] },
  { day: 35, phase: "DSA", topic: "Prefix Sum", subtopics: [{title: "Range sum queries", url: "https://leetcode.com/tag/prefix-sum/", difficulty: "medium", type: "practice"}] },
  { day: 36, phase: "DSA", topic: "Binary Search Basics", subtopics: [{title: "Implementation & Mid-point overflow", url: "https://leetcode.com/problems/binary-search/", difficulty: "easy", type: "practice"}] },
  { day: 37, phase: "DSA", topic: "Advanced Binary Search", subtopics: [{title: "Search in rotated arrays", url: "https://leetcode.com/problems/search-in-rotated-sorted-array/", difficulty: "hard", type: "practice"}] },
  { day: 38, phase: "DSA", topic: "Sorting I", subtopics: [{title: "Bubble, Selection, Insertion Sort", url: "https://www.youtube.com/results?search_query=Sorting+algorithms", difficulty: "easy", type: "theory"}] },
  { day: 39, phase: "DSA", topic: "Sorting II", subtopics: [{title: "Merge Sort & Divide and Conquer", url: "https://www.youtube.com/results?search_query=Merge+sort", difficulty: "medium", type: "theory"}] },
  { day: 40, phase: "DSA", topic: "Sorting III", subtopics: [{title: "Quick Sort & Partitioning", url: "https://www.youtube.com/results?search_query=Quick+sort", difficulty: "medium", type: "practice"}] },
  { day: 41, phase: "DSA", topic: "Linked Lists Basics", subtopics: [{title: "Singly linked lists, traversal, reversal", url: "https://leetcode.com/problems/reverse-linked-list/", difficulty: "medium", type: "practice"}] },
  { day: 42, phase: "DSA", topic: "Fast & Slow Pointers", subtopics: [{title: "Cycle detection (Floyd's)", url: "https://leetcode.com/problems/linked-list-cycle/", difficulty: "medium", type: "practice"}] },
  { day: 43, phase: "DSA", topic: "Doubly Linked Lists", subtopics: [{title: "Insertion & Deletion", url: "https://www.youtube.com/results?search_query=Doubly+linked+list", difficulty: "medium", type: "practice"}] },
  { day: 44, phase: "DSA", topic: "Stacks", subtopics: [{title: "LIFO, Valid Parentheses", url: "https://leetcode.com/problems/valid-parentheses/", difficulty: "easy", type: "practice"}] },
  { day: 45, phase: "DSA", topic: "Monotonic Stacks", subtopics: [{title: "Next Greater Element", url: "https://leetcode.com/tag/monotonic-stack/", difficulty: "hard", type: "practice"}] },
  { day: 46, phase: "DSA", topic: "Queues", subtopics: [{title: "FIFO, Circular queues", url: "https://www.youtube.com/results?search_query=Queue+data+structure", difficulty: "easy", type: "practice"}] },
  { day: 47, phase: "DSA", topic: "Hash Maps & Sets", subtopics: [{title: "Collision handling, O(1) lookups", url: "https://leetcode.com/tag/hash-table/", difficulty: "easy", type: "practice"}] },
  { day: 48, phase: "DSA", topic: "Hashing Patterns", subtopics: [{title: "Two Sum, Frequency maps", url: "https://leetcode.com/problems/two-sum/", difficulty: "easy", type: "practice"}] },
  { day: 49, phase: "DSA", topic: "Strings Basics", subtopics: [{title: "Immutability & ASCII manipulation", url: "https://leetcode.com/tag/string/", difficulty: "easy", type: "practice"}] },
  { day: 50, phase: "DSA", topic: "Advanced Strings", subtopics: [{title: "Anagrams, Palindromes, Trie Basics", url: "https://leetcode.com/problems/valid-anagram/", difficulty: "medium", type: "practice"}] },
  { day: 51, phase: "DSA", topic: "Binary Trees Basics", subtopics: [{title: "Nodes, Depth, Height", url: "https://www.youtube.com/results?search_query=Binary+tree+basics", difficulty: "easy", type: "theory"}] },
  { day: 52, phase: "DSA", topic: "Tree Traversals", subtopics: [{title: "Inorder, Preorder, Postorder", url: "https://leetcode.com/problems/binary-tree-inorder-traversal/", difficulty: "medium", type: "practice"}] },
  { day: 53, phase: "DSA", topic: "Breadth-First Search (BFS)", subtopics: [{title: "Level order traversal using Queues", url: "https://leetcode.com/problems/binary-tree-level-order-traversal/", difficulty: "medium", type: "practice"}] },
  { day: 54, phase: "DSA", topic: "Depth-First Search (DFS)", subtopics: [{title: "Recursion in trees", url: "https://leetcode.com/problems/maximum-depth-of-binary-tree/", difficulty: "medium", type: "practice"}] },
  { day: 55, phase: "DSA", topic: "Binary Search Trees (BST)", subtopics: [{title: "Properties, Search, Insert", url: "https://leetcode.com/problems/search-in-a-binary-search-tree/", difficulty: "medium", type: "practice"}] },
  { day: 56, phase: "DSA", topic: "Lowest Common Ancestor", subtopics: [{title: "LCA in BST and Binary Trees", url: "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/", difficulty: "hard", type: "practice"}] },
  { day: 57, phase: "DSA", topic: "Heaps Basics", subtopics: [{title: "Min-Heap vs Max-Heap", url: "https://www.youtube.com/results?search_query=Heap+data+structure", difficulty: "medium", type: "theory"}] },
  { day: 58, phase: "DSA", topic: "Heapify & Priority Queues", subtopics: [{title: "Kth Largest Element", url: "https://leetcode.com/problems/kth-largest-element-in-an-array/", difficulty: "medium", type: "practice"}] },
  { day: 59, phase: "DSA", topic: "Top K Elements Pattern", subtopics: [{title: "Top K Frequent Elements", url: "https://leetcode.com/problems/top-k-frequent-elements/", difficulty: "medium", type: "practice"}] },
  { day: 60, phase: "DSA", topic: "Merge Intervals Pattern", subtopics: [{title: "Overlapping intervals", url: "https://leetcode.com/problems/merge-intervals/", difficulty: "medium", type: "practice"}] },
  { day: 61, phase: "DSA", topic: "Graph Representation", subtopics: [{title: "Adjacency Matrix vs List", url: "https://www.youtube.com/results?search_query=Graph+representation", difficulty: "easy", type: "theory"}] },
  { day: 62, phase: "DSA", topic: "Graph BFS", subtopics: [{title: "Shortest path in unweighted graphs", url: "https://leetcode.com/problems/rotting-oranges/", difficulty: "medium", type: "practice"}] },
  { day: 63, phase: "DSA", topic: "Graph DFS", subtopics: [{title: "Connected components, Number of Islands", url: "https://leetcode.com/problems/number-of-islands/", difficulty: "medium", type: "practice"}] },
  { day: 64, phase: "DSA", topic: "Topological Sort", subtopics: [{title: "Course Schedule", url: "https://leetcode.com/problems/course-schedule/", difficulty: "hard", type: "practice"}] },
  { day: 65, phase: "DSA", topic: "Dijkstra's Algorithm", subtopics: [{title: "Shortest path in weighted graphs", url: "https://www.youtube.com/results?search_query=Dijkstras+algorithm", difficulty: "hard", type: "theory"}] },
  { day: 66, phase: "DSA", topic: "Minimum Spanning Tree", subtopics: [{title: "Prim's & Kruskal's", url: "https://www.youtube.com/results?search_query=Minimum+spanning+tree", difficulty: "hard", type: "theory"}] },
  { day: 67, phase: "DSA", topic: "Disjoint Set (Union-Find)", subtopics: [{title: "Cycle detection in graphs", url: "https://leetcode.com/problems/redundant-connection/", difficulty: "hard", type: "practice"}] },
  { day: 68, phase: "DSA", topic: "Recursion Basics", subtopics: [{title: "Base cases & Call stack", url: "https://www.youtube.com/results?search_query=Recursion+explained", difficulty: "easy", type: "theory"}] },
  { day: 69, phase: "DSA", topic: "Backtracking Intro", subtopics: [{title: "Subsets, Permutations", url: "https://leetcode.com/problems/subsets/", difficulty: "medium", type: "practice"}] },
  { day: 70, phase: "DSA", topic: "Advanced Backtracking", subtopics: [{title: "N-Queens, Sudoku Solver", url: "https://leetcode.com/problems/n-queens/", difficulty: "hard", type: "practice"}] },
  { day: 71, phase: "DSA", topic: "DP Basics", subtopics: [{title: "Memoization vs Tabulation", url: "https://www.youtube.com/results?search_query=Dynamic+programming", difficulty: "medium", type: "theory"}] },
  { day: 72, phase: "DSA", topic: "1D DP - Fibonacci Style", subtopics: [{title: "Climbing Stairs, House Robber", url: "https://leetcode.com/problems/climbing-stairs/", difficulty: "easy", type: "practice"}] },
  { day: 73, phase: "DSA", topic: "1D DP - Longest Increasing Subsequence", subtopics: [{title: "LIS pattern", url: "https://leetcode.com/problems/longest-increasing-subsequence/", difficulty: "medium", type: "practice"}] },
  { day: 74, phase: "DSA", topic: "2D DP - Grid Traveler", subtopics: [{title: "Unique Paths", url: "https://leetcode.com/problems/unique-paths/", difficulty: "medium", type: "practice"}] },
  { day: 75, phase: "DSA", topic: "2D DP - Knapsack Problem", subtopics: [{title: "0/1 Knapsack basics", url: "https://www.youtube.com/results?search_query=0+1+knapsack", difficulty: "hard", type: "theory"}] },
  { day: 76, phase: "DSA", topic: "2D DP - Longest Common Subsequence", subtopics: [{title: "LCS implementation", url: "https://leetcode.com/problems/longest-common-subsequence/", difficulty: "hard", type: "practice"}] },
  { day: 77, phase: "DSA", topic: "Greedy Algorithms", subtopics: [{title: "Jump Game, Activity Selection", url: "https://leetcode.com/problems/jump-game/", difficulty: "medium", type: "practice"}] },
  { day: 78, phase: "DSA", topic: "Bit Manipulation", subtopics: [{title: "AND, OR, XOR, Shifts", url: "https://leetcode.com/problems/single-number/", difficulty: "easy", type: "practice"}] },
  { day: 79, phase: "DSA", topic: "Blind 75 - Arrays", subtopics: [{title: "Solve core array problems", url: "https://leetcode.com/discuss/general-discussion/460599/blind-75-leetcode-questions", difficulty: "medium", type: "practice"}] },
  { day: 80, phase: "DSA", topic: "Blind 75 - Strings", subtopics: [{title: "Solve core string problems", url: "https://leetcode.com/discuss/general-discussion/460599/blind-75-leetcode-questions", difficulty: "medium", type: "practice"}] },
  { day: 81, phase: "DSA", topic: "Blind 75 - Trees", subtopics: [{title: "Solve core tree problems", url: "https://leetcode.com/discuss/general-discussion/460599/blind-75-leetcode-questions", difficulty: "medium", type: "practice"}] },
  { day: 82, phase: "DSA", topic: "Blind 75 - Graphs", subtopics: [{title: "Solve core graph problems", url: "https://leetcode.com/discuss/general-discussion/460599/blind-75-leetcode-questions", difficulty: "hard", type: "practice"}] },
  { day: 83, phase: "DSA", topic: "Blind 75 - DP", subtopics: [{title: "Solve core DP problems", url: "https://leetcode.com/discuss/general-discussion/460599/blind-75-leetcode-questions", difficulty: "hard", type: "practice"}] },
  { day: 84, phase: "DSA", topic: "Mock Interview 1", subtopics: [{title: "Time yourself on 2 mediums", url: "https://pramp.com/", difficulty: "hard", type: "project"}] },
  { day: 85, phase: "DSA", topic: "Mock Interview 2", subtopics: [{title: "Time yourself on 1 hard", url: "https://pramp.com/", difficulty: "hard", type: "project"}] },
  { day: 86, phase: "DSA", topic: "Review Weak Areas", subtopics: [{title: "Revisit failed problems", url: "https://leetcode.com/", difficulty: "medium", type: "practice"}] },
  { day: 87, phase: "DSA", topic: "System Design vs DSA", subtopics: [{title: "Connecting structures to scaling", url: "https://github.com/", difficulty: "medium", type: "theory"}] },
  { day: 88, phase: "DSA", topic: "Competitive Programming Intro", subtopics: [{title: "Codeforces/CodeChef basics", url: "https://codeforces.com/", difficulty: "hard", type: "practice"}] },
  { day: 89, phase: "DSA", topic: "Final Grind", subtopics: [{title: "Solve 5 random mediums", url: "https://leetcode.com/problemset/all/", difficulty: "hard", type: "practice"}] },
  { day: 90, phase: "DSA", topic: "DSA Ready", subtopics: [{title: "Consistent daily problem solving from here", url: "https://leetcode.com/", difficulty: "easy", type: "theory"}] }
];
