const learningPath = [
  { day: 1, phase: "Phase 1", topic: "Java Execution Model", subtopics: [{title: "JDK, JRE, JVM & Bytecode", url: "https://www.youtube.com/results?search_query=JDK+JRE+JVM+explained", difficulty: "easy", type: "theory"}, {title: "Why Java is platform independent", url: "https://docs.oracle.com/javase/tutorial/getStarted/intro/definition.html", difficulty: "easy", type: "theory"}] },
  { day: 2, phase: "Phase 1", topic: "Java Syntax + First Program", subtopics: [{title: "main() method & Class structure", url: "https://www.youtube.com/results?search_query=Java+main+method+explained", difficulty: "easy", type: "theory"}, {title: "System.out.println & Entry logic", url: "https://docs.oracle.com/javase/tutorial/getStarted/application/index.html", difficulty: "easy", type: "theory"}] },
  { day: 3, phase: "Phase 1", topic: "Variables & Data Types", subtopics: [{title: "int, float, double, char, boolean", url: "https://www.youtube.com/results?search_query=Java+variables+and+data+types", difficulty: "easy", type: "theory"}, {title: "Memory usage & Type conversion", url: "https://www.w3schools.com/java/java_data_types.asp", difficulty: "medium", type: "theory"}] },
  { day: 4, phase: "Phase 1", topic: "Operators", subtopics: [{title: "Arithmetic, Logical, Relational", url: "https://www.youtube.com/results?search_query=Java+operators+tutorial", difficulty: "easy", type: "theory"}, {title: "Short-circuit evaluation (&& vs &)", url: "https://www.geeksforgeeks.org/operators-in-java/", difficulty: "medium", type: "theory"}] },
  { day: 5, phase: "Phase 1", topic: "Conditionals", subtopics: [{title: "if-else, nested if, switch", url: "https://www.youtube.com/results?search_query=Java+if+else+switch", difficulty: "easy", type: "theory"}, {title: "Edge cases & when to use switch", url: "https://www.w3schools.com/java/java_conditions.asp", difficulty: "medium", type: "practice"}] },
  { day: 6, phase: "Phase 1", topic: "Loops", subtopics: [{title: "for, while, do-while", url: "https://www.youtube.com/results?search_query=Java+loops+tutorial", difficulty: "easy", type: "theory"}, {title: "Infinite loops & optimization", url: "https://www.geeksforgeeks.org/loops-in-java/", difficulty: "medium", type: "practice"}] },
  { day: 7, phase: "Phase 1", topic: "REVISION + PRACTICE", subtopics: [{title: "Solve 10 problems (loops + conditions)", url: "https://leetcode.com/problemset/all/?difficulty=EASY&page=1", difficulty: "hard", type: "practice"}] },
  { day: 8, phase: "Phase 1", topic: "Arrays (Basics)", subtopics: [{title: "Declaration, Initialization, Traversal", url: "https://www.youtube.com/results?search_query=Java+arrays+basics", difficulty: "easy", type: "theory"}, {title: "Indexing & Off-by-one errors", url: "https://www.w3schools.com/java/java_arrays.asp", difficulty: "medium", type: "practice"}] },
  { day: 9, phase: "Phase 1", topic: "Arrays (Advanced)", subtopics: [{title: "Prefix sum & Sliding window", url: "https://www.youtube.com/results?search_query=Sliding+window+algorithm+Java", difficulty: "hard", type: "practice"}, {title: "Pattern recognition", url: "https://www.geeksforgeeks.org/prefix-sum-array-implementation-applications-competitive-programming/", difficulty: "medium", type: "practice"}] },
  { day: 10, phase: "Phase 1", topic: "2D Arrays", subtopics: [{title: "Matrix traversal, Row vs column", url: "https://www.youtube.com/results?search_query=Java+2D+arrays", difficulty: "medium", type: "theory"}, {title: "How memory is stored in 2D", url: "https://www.geeksforgeeks.org/multidimensional-arrays-in-java/", difficulty: "medium", type: "theory"}] },
  { day: 11, phase: "Phase 1", topic: "Strings Basics", subtopics: [{title: "String creation & Methods", url: "https://www.youtube.com/results?search_query=Java+String+methods", difficulty: "easy", type: "theory"}, {title: "Immutability", url: "https://www.w3schools.com/java/java_strings.asp", difficulty: "medium", type: "theory"}] },
  { day: 12, phase: "Phase 1", topic: "StringBuilder", subtopics: [{title: "Mutable strings & Performance", url: "https://www.youtube.com/results?search_query=Java+StringBuilder+tutorial", difficulty: "medium", type: "theory"}, {title: "String vs StringBuilder", url: "https://www.geeksforgeeks.org/stringbuilder-class-in-java-with-examples/", difficulty: "easy", type: "theory"}] },
  { day: 13, phase: "Phase 1", topic: "String Problems", subtopics: [{title: "Palindrome logic", url: "https://leetcode.com/problems/valid-palindrome/", difficulty: "medium", type: "practice"}, {title: "Frequency count & logic building", url: "https://www.youtube.com/results?search_query=Java+string+frequency+count", difficulty: "hard", type: "practice"}] },
  { day: 14, phase: "Phase 1", topic: "REVISION", subtopics: [{title: "Review Arrays and Strings", url: "https://github.com/", difficulty: "medium", type: "practice"}] },
  { day: 15, phase: "Phase 1", topic: "OOP Intro", subtopics: [{title: "Class vs Object & Real-world mapping", url: "https://www.youtube.com/results?search_query=Java+OOP+concepts", difficulty: "easy", type: "theory"}, {title: "OOP Basics", url: "https://www.w3schools.com/java/java_oop.asp", difficulty: "easy", type: "theory"}] },
  { day: 16, phase: "Phase 1", topic: "Encapsulation", subtopics: [{title: "Access modifiers & Getters/setters", url: "https://www.youtube.com/results?search_query=Java+Encapsulation", difficulty: "easy", type: "theory"}, {title: "Data hiding", url: "https://www.geeksforgeeks.org/encapsulation-in-java/", difficulty: "medium", type: "theory"}] },
  { day: 17, phase: "Phase 1", topic: "Inheritance", subtopics: [{title: "Types & extends keyword", url: "https://www.youtube.com/results?search_query=Java+Inheritance", difficulty: "medium", type: "theory"}, {title: "Code reuse", url: "https://www.w3schools.com/java/java_inheritance.asp", difficulty: "easy", type: "theory"}] },
  { day: 18, phase: "Phase 1", topic: "Polymorphism", subtopics: [{title: "Method overloading vs Overriding", url: "https://www.youtube.com/results?search_query=Java+Polymorphism", difficulty: "medium", type: "theory"}, {title: "Compile vs runtime", url: "https://www.geeksforgeeks.org/polymorphism-in-java/", difficulty: "hard", type: "theory"}] },
  { day: 19, phase: "Phase 1", topic: "Abstraction", subtopics: [{title: "Abstract class vs Interface", url: "https://www.youtube.com/results?search_query=Java+Abstraction+and+Interfaces", difficulty: "medium", type: "theory"}, {title: "When to use interface", url: "https://www.w3schools.com/java/java_abstract.asp", difficulty: "medium", type: "theory"}] },
  { day: 20, phase: "Phase 1", topic: "OOP PRACTICE", subtopics: [{title: "Build: Simple class-based system", url: "https://github.com/", difficulty: "hard", type: "project"}] },
  
  // --- PHASE 2: JAVA BACKEND CORE ---
  { day: 21, phase: "Phase 2", topic: "Collections Intro", subtopics: [{title: "ArrayList & List interface", url: "https://www.youtube.com/results?search_query=Java+ArrayList+tutorial", difficulty: "easy", type: "theory"}, {title: "Dynamic resizing", url: "https://www.w3schools.com/java/java_arraylist.asp", difficulty: "medium", type: "theory"}] },
  { day: 22, phase: "Phase 2", topic: "HashMap", subtopics: [{title: "Key-value pairs & Hashing", url: "https://www.youtube.com/results?search_query=Java+HashMap+tutorial", difficulty: "medium", type: "theory"}, {title: "Time complexity", url: "https://www.geeksforgeeks.org/java-util-hashmap-in-java-with-examples/", difficulty: "hard", type: "theory"}] },
  { day: 23, phase: "Phase 2", topic: "HashSet", subtopics: [{title: "Unique elements & Use cases", url: "https://www.youtube.com/results?search_query=Java+HashSet", difficulty: "easy", type: "theory"}] },
  { day: 24, phase: "Phase 2", topic: "Exceptions", subtopics: [{title: "try-catch & finally", url: "https://www.youtube.com/results?search_query=Java+Exception+Handling", difficulty: "medium", type: "theory"}, {title: "Error handling flow", url: "https://www.geeksforgeeks.org/exceptions-in-java/", difficulty: "medium", type: "practice"}] },
  { day: 25, phase: "Phase 2", topic: "Custom Exceptions", subtopics: [{title: "Creating custom exception classes", url: "https://www.youtube.com/results?search_query=Java+Custom+Exceptions", difficulty: "medium", type: "practice"}] },
  { day: 26, phase: "Phase 2", topic: "File Handling", subtopics: [{title: "Reading & Writing files", url: "https://www.youtube.com/results?search_query=Java+File+Handling", difficulty: "medium", type: "practice"}] },
  { day: 27, phase: "Phase 2", topic: "Practice", subtopics: [{title: "Practice Collections & Exceptions", url: "https://github.com/", difficulty: "hard", type: "practice"}] },
  { day: 28, phase: "Phase 2", topic: "Mini Project", subtopics: [{title: "Build command-line application", url: "https://github.com/", difficulty: "hard", type: "project"}] },
  { day: 29, phase: "Phase 2", topic: "Improve Project", subtopics: [{title: "Add error handling & Refactor", url: "https://github.com/", difficulty: "medium", type: "project"}] },
  { day: 30, phase: "Phase 2", topic: "FINAL REVISION", subtopics: [{title: "Review Java Core & OOP", url: "https://github.com/", difficulty: "medium", type: "practice"}] },

  // --- PHASE 3: SPRING BOOT & DB ---
  { day: 31, phase: "Phase 3", topic: "Internet & Web Basics", subtopics: [{title: "Client vs Server, Request -> Response", url: "https://www.youtube.com/results?search_query=How+the+internet+works", difficulty: "easy", type: "theory"}, {title: "DNS basics", url: "https://developer.mozilla.org/en-US/docs/Learn/Common_questions/Web_mechanics/How_does_the_Internet_work", difficulty: "easy", type: "theory"}] },
  { day: 32, phase: "Phase 3", topic: "HTTP Deep Dive", subtopics: [{title: "GET, POST, PUT, DELETE", url: "https://www.youtube.com/results?search_query=HTTP+methods+and+status+codes", difficulty: "medium", type: "theory"}, {title: "Idempotency & Stateless nature", url: "https://restfulapi.net/http-methods/", difficulty: "hard", type: "theory"}] },
  { day: 33, phase: "Phase 3", topic: "REST API Concepts", subtopics: [{title: "REST principles & Endpoints", url: "https://www.youtube.com/results?search_query=What+is+a+REST+API", difficulty: "medium", type: "theory"}, {title: "Naming conventions", url: "https://restfulapi.net/", difficulty: "easy", type: "theory"}] },
  { day: 34, phase: "Phase 3", topic: "JSON", subtopics: [{title: "JSON structure & Serialization", url: "https://www.youtube.com/results?search_query=JSON+tutorial", difficulty: "easy", type: "theory"}] },
  { day: 35, phase: "Phase 3", topic: "Postman Practice", subtopics: [{title: "Sending requests & Testing APIs", url: "https://www.youtube.com/results?search_query=Postman+API+testing+tutorial", difficulty: "medium", type: "practice"}] },
  { day: 36, phase: "Phase 3", topic: "Spring Boot Intro", subtopics: [{title: "What is Spring Boot & Project structure", url: "https://www.youtube.com/results?search_query=Spring+Boot+tutorial+for+beginners", difficulty: "medium", type: "theory"}] },
  { day: 37, phase: "Phase 3", topic: "Spring Boot Setup", subtopics: [{title: "Creating project & Dependencies", url: "https://start.spring.io/", difficulty: "easy", type: "practice"}, {title: "Maven basics", url: "https://www.youtube.com/results?search_query=Maven+tutorial+for+beginners", difficulty: "medium", type: "theory"}] },
  { day: 38, phase: "Phase 3", topic: "Controllers", subtopics: [{title: "@RestController & @RequestMapping", url: "https://www.youtube.com/results?search_query=Spring+Boot+RestController", difficulty: "medium", type: "practice"}] },
  { day: 39, phase: "Phase 3", topic: "Request Handling", subtopics: [{title: "@GetMapping, @PostMapping, Path variables", url: "https://www.youtube.com/results?search_query=Spring+Boot+GetMapping+PostMapping", difficulty: "medium", type: "practice"}] },
  { day: 40, phase: "Phase 3", topic: "Request Body", subtopics: [{title: "@RequestBody & JSON to object mapping", url: "https://www.youtube.com/results?search_query=Spring+Boot+RequestBody", difficulty: "hard", type: "practice"}] },
  { day: 41, phase: "Phase 3", topic: "Response Handling", subtopics: [{title: "ResponseEntity & Status codes", url: "https://www.youtube.com/results?search_query=Spring+Boot+ResponseEntity", difficulty: "medium", type: "practice"}] },
  { day: 42, phase: "Phase 3", topic: "REVISION + PRACTICE", subtopics: [{title: "Build simple APIs: Hello API, GET/POST", url: "https://github.com/", difficulty: "hard", type: "project"}] },
  { day: 43, phase: "Phase 3", topic: "Dependency Injection 🚨", subtopics: [{title: "@Autowired & Beans", url: "https://www.youtube.com/results?search_query=Spring+Boot+Dependency+Injection", difficulty: "hard", type: "theory"}] },
  { day: 44, phase: "Phase 3", topic: "Layered Architecture 🚨", subtopics: [{title: "Controller, Service, Repository", url: "https://www.youtube.com/results?search_query=Spring+Boot+Layered+Architecture", difficulty: "hard", type: "theory"}] },
  { day: 45, phase: "Phase 3", topic: "Service Layer", subtopics: [{title: "Business logic & Clean structure", url: "https://www.youtube.com/results?search_query=Spring+Boot+Service+Layer", difficulty: "medium", type: "practice"}] },
  { day: 46, phase: "Phase 3", topic: "Database Intro", subtopics: [{title: "RDBMS basics, Tables, rows, columns", url: "https://www.youtube.com/results?search_query=Relational+Database+Concepts", difficulty: "easy", type: "theory"}] },
  { day: 47, phase: "Phase 3", topic: "SQL Basics", subtopics: [{title: "SELECT, INSERT, UPDATE, DELETE", url: "https://www.youtube.com/results?search_query=SQL+Basics+Tutorial", difficulty: "medium", type: "practice"}] },
  { day: 48, phase: "Phase 3", topic: "SQL Advanced", subtopics: [{title: "WHERE, ORDER BY, LIMIT", url: "https://www.youtube.com/results?search_query=SQL+Advanced+Queries", difficulty: "medium", type: "practice"}] },
  { day: 49, phase: "Phase 3", topic: "JOINS 🚨", subtopics: [{title: "INNER JOIN, LEFT JOIN", url: "https://www.youtube.com/results?search_query=SQL+Joins+Explained", difficulty: "hard", type: "practice"}] },
  { day: 50, phase: "Phase 3", topic: "INDEXING", subtopics: [{title: "Index basics & Query performance", url: "https://www.youtube.com/results?search_query=SQL+Indexing+Explained", difficulty: "medium", type: "theory"}] },
  { day: 51, phase: "Phase 3", topic: "REVISION + SQL PRACTICE", subtopics: [{title: "Practice SQL queries", url: "https://leetcode.com/problemset/database/", difficulty: "hard", type: "practice"}] },
  { day: 52, phase: "Phase 3", topic: "JPA Intro", subtopics: [{title: "ORM concept & Entities", url: "https://www.youtube.com/results?search_query=Spring+Data+JPA+Tutorial", difficulty: "medium", type: "theory"}] },
  { day: 53, phase: "Phase 3", topic: "Entity Mapping", subtopics: [{title: "@Entity & @Id, Primary keys", url: "https://www.youtube.com/results?search_query=JPA+Entity+Mapping", difficulty: "medium", type: "practice"}] },
  { day: 54, phase: "Phase 3", topic: "Repository Layer", subtopics: [{title: "JpaRepository & CRUD operations", url: "https://www.youtube.com/results?search_query=Spring+Data+JpaRepository", difficulty: "medium", type: "practice"}] },
  { day: 55, phase: "Phase 3", topic: "Relationships 🚨", subtopics: [{title: "One-to-One, One-to-Many", url: "https://www.youtube.com/results?search_query=JPA+Relationships+One+to+Many", difficulty: "hard", type: "practice"}] },
  { day: 56, phase: "Phase 3", topic: "Connecting DB to Spring Boot", subtopics: [{title: "application.properties & DB config", url: "https://www.youtube.com/results?search_query=Spring+Boot+connect+to+MySQL", difficulty: "medium", type: "practice"}] },
  { day: 57, phase: "Phase 3", topic: "CRUD API with DB", subtopics: [{title: "Full flow: Controller -> Service -> DB", url: "https://www.youtube.com/results?search_query=Spring+Boot+CRUD+API+with+Database", difficulty: "hard", type: "project"}] },
  { day: 58, phase: "Phase 3", topic: "Error Handling", subtopics: [{title: "Exception handling in APIs", url: "https://www.youtube.com/results?search_query=Spring+Boot+Exception+Handling", difficulty: "medium", type: "practice"}] },
  { day: 59, phase: "Phase 3", topic: "Backend Project 🚨", subtopics: [{title: "Build: User management system (CRUD)", url: "https://github.com/", difficulty: "hard", type: "project"}] },
  { day: 60, phase: "Phase 3", topic: "Improve Project", subtopics: [{title: "Add Validation & Better responses", url: "https://github.com/", difficulty: "medium", type: "project"}] },

  // --- PHASE 4: ADVANCED APIs & AUTH ---
  { day: 61, phase: "Phase 4", topic: "API Design Best Practices", subtopics: [{title: "Naming conventions & Versioning", url: "https://www.youtube.com/results?search_query=REST+API+Best+Practices", difficulty: "easy", type: "theory"}] },
  { day: 62, phase: "Phase 4", topic: "DTO Pattern 🚨", subtopics: [{title: "What is DTO, Entity vs DTO", url: "https://www.youtube.com/results?search_query=Spring+Boot+DTO+Pattern", difficulty: "hard", type: "theory"}] },
  { day: 63, phase: "Phase 4", topic: "Validation", subtopics: [{title: "@Valid & Field validation", url: "https://www.youtube.com/results?search_query=Spring+Boot+Validation", difficulty: "medium", type: "practice"}] },
  { day: 64, phase: "Phase 4", topic: "Global Exception Handling 🚨", subtopics: [{title: "@ControllerAdvice & Custom errors", url: "https://www.youtube.com/results?search_query=Spring+Boot+ControllerAdvice", difficulty: "hard", type: "practice"}] },
  { day: 65, phase: "Phase 4", topic: "Logging", subtopics: [{title: "Log levels (Debug vs error)", url: "https://www.youtube.com/results?search_query=Spring+Boot+Logging", difficulty: "medium", type: "practice"}] },
  { day: 66, phase: "Phase 4", topic: "Authentication Basics", subtopics: [{title: "Session vs token (Stateless vs stateful)", url: "https://www.youtube.com/results?search_query=Session+vs+Token+Authentication", difficulty: "medium", type: "theory"}] },
  { day: 67, phase: "Phase 4", topic: "JWT Intro 🚨", subtopics: [{title: "Structure of JWT & Token flow", url: "https://www.youtube.com/results?search_query=What+is+JWT", difficulty: "hard", type: "theory"}] },
  { day: 68, phase: "Phase 4", topic: "JWT Implementation", subtopics: [{title: "Generate token & Validate token", url: "https://www.youtube.com/results?search_query=Spring+Boot+JWT+Implementation", difficulty: "hard", type: "practice"}] },
  { day: 69, phase: "Phase 4", topic: "Spring Security Basics", subtopics: [{title: "Security configuration & Filters", url: "https://www.youtube.com/results?search_query=Spring+Security+Tutorial", difficulty: "hard", type: "theory"}] },
  { day: 70, phase: "Phase 4", topic: "Secure APIs", subtopics: [{title: "Role-based access", url: "https://www.youtube.com/results?search_query=Spring+Security+Role+Based+Access", difficulty: "hard", type: "practice"}] },
  { day: 71, phase: "Phase 4", topic: "REVISION + PRACTICE", subtopics: [{title: "Build: Secure API endpoints", url: "https://github.com/", difficulty: "hard", type: "project"}] },
  { day: 72, phase: "Phase 4", topic: "Pagination", subtopics: [{title: "Limit & offset, Pageable", url: "https://www.youtube.com/results?search_query=Spring+Boot+Pagination", difficulty: "medium", type: "practice"}] },
  { day: 73, phase: "Phase 4", topic: "Sorting", subtopics: [{title: "Sorting results", url: "https://www.youtube.com/results?search_query=Spring+Boot+Sorting", difficulty: "medium", type: "practice"}] },
  { day: 74, phase: "Phase 4", topic: "Caching Basics", subtopics: [{title: "What is caching & When to use", url: "https://www.youtube.com/results?search_query=Spring+Boot+Caching", difficulty: "easy", type: "theory"}] },
  { day: 75, phase: "Phase 4", topic: "Redis Intro", subtopics: [{title: "In-memory storage", url: "https://www.youtube.com/results?search_query=Spring+Boot+Redis+Tutorial", difficulty: "medium", type: "practice"}] },
  { day: 76, phase: "Phase 4", topic: "Async Processing", subtopics: [{title: "@Async & Background tasks", url: "https://www.youtube.com/results?search_query=Spring+Boot+Async", difficulty: "medium", type: "practice"}] },
  { day: 77, phase: "Phase 4", topic: "File Upload APIs", subtopics: [{title: "Multipart file handling", url: "https://www.youtube.com/results?search_query=Spring+Boot+File+Upload", difficulty: "medium", type: "practice"}] },
  { day: 78, phase: "Phase 4", topic: "API Documentation", subtopics: [{title: "Swagger/OpenAPI", url: "https://www.youtube.com/results?search_query=Spring+Boot+Swagger+OpenAPI", difficulty: "easy", type: "practice"}] },
  { day: 79, phase: "Phase 4", topic: "Testing Basics", subtopics: [{title: "Unit testing & Integration testing", url: "https://www.youtube.com/results?search_query=Spring+Boot+Testing+JUnit", difficulty: "hard", type: "practice"}] },
  { day: 80, phase: "Phase 4", topic: "Debugging Skills", subtopics: [{title: "Logs & Breakpoints", url: "https://www.youtube.com/results?search_query=How+to+debug+Spring+Boot", difficulty: "medium", type: "practice"}] },
  { day: 81, phase: "Phase 4", topic: "Mini Project Planning", subtopics: [{title: "Plan: Advanced backend system", url: "https://github.com/", difficulty: "hard", type: "project"}] },
  { day: 82, phase: "Phase 4", topic: "Build Project", subtopics: [{title: "Auth system (JWT)", url: "https://github.com/", difficulty: "hard", type: "project"}] },
  { day: 83, phase: "Phase 4", topic: "Build Project", subtopics: [{title: "CRUD APIs Part 1", url: "https://github.com/", difficulty: "hard", type: "project"}] },
  { day: 84, phase: "Phase 4", topic: "Build Project", subtopics: [{title: "CRUD APIs Part 2", url: "https://github.com/", difficulty: "hard", type: "project"}] },
  { day: 85, phase: "Phase 4", topic: "Build Project", subtopics: [{title: "Validation Layer", url: "https://github.com/", difficulty: "hard", type: "project"}] },
  { day: 86, phase: "Phase 4", topic: "Improve Project", subtopics: [{title: "Add Pagination", url: "https://github.com/", difficulty: "medium", type: "project"}] },
  { day: 87, phase: "Phase 4", topic: "Improve Project", subtopics: [{title: "Add Error handling", url: "https://github.com/", difficulty: "medium", type: "project"}] },
  { day: 88, phase: "Phase 4", topic: "Improve Project", subtopics: [{title: "Add Logging", url: "https://github.com/", difficulty: "easy", type: "project"}] },
  { day: 89, phase: "Phase 4", topic: "Testing + Fixing", subtopics: [{title: "Run Tests & Fix Bugs", url: "https://github.com/", difficulty: "hard", type: "project"}] },
  { day: 90, phase: "Phase 4", topic: "FINAL REVIEW 🚨", subtopics: [{title: "Explain Auth, API flow", url: "https://github.com/", difficulty: "medium", type: "theory"}] },

  // --- PHASE 5: PYTHON + ML FOUNDATION ---
  { day: 91, phase: "Phase 5", topic: "Python Basics", subtopics: [{title: "Variables, Data types", url: "https://www.youtube.com/results?search_query=Python+Crash+Course", difficulty: "easy", type: "theory"}] },
  { day: 92, phase: "Phase 5", topic: "Control Flow", subtopics: [{title: "if-else, loops", url: "https://www.youtube.com/results?search_query=Python+Control+Flow", difficulty: "easy", type: "practice"}] },
  { day: 93, phase: "Phase 5", topic: "Data Structures", subtopics: [{title: "Lists, Tuples, Sets, Dictionaries", url: "https://www.youtube.com/results?search_query=Python+Data+Structures", difficulty: "medium", type: "practice"}] },
  { day: 94, phase: "Phase 5", topic: "Functions", subtopics: [{title: "Definition, Arguments, Returns", url: "https://www.youtube.com/results?search_query=Python+Functions", difficulty: "medium", type: "practice"}] },
  { day: 95, phase: "Phase 5", topic: "File Handling", subtopics: [{title: "Reading/Writing files", url: "https://www.youtube.com/results?search_query=Python+File+Handling", difficulty: "medium", type: "practice"}] },
  { day: 96, phase: "Phase 5", topic: "NumPy Basics 🚨", subtopics: [{title: "Arrays, Shape, Indexing", url: "https://www.youtube.com/results?search_query=NumPy+Tutorial", difficulty: "medium", type: "practice"}] },
  { day: 97, phase: "Phase 5", topic: "NumPy Operations", subtopics: [{title: "Vector operations & Broadcasting", url: "https://www.youtube.com/results?search_query=NumPy+Operations+and+Broadcasting", difficulty: "hard", type: "practice"}] },
  { day: 98, phase: "Phase 5", topic: "Pandas Basics 🚨", subtopics: [{title: "DataFrame & Series", url: "https://www.youtube.com/results?search_query=Pandas+Tutorial", difficulty: "medium", type: "practice"}] },
  { day: 99, phase: "Phase 5", topic: "Pandas Operations", subtopics: [{title: "Filtering, Grouping, Aggregation", url: "https://www.youtube.com/results?search_query=Pandas+Data+Cleaning", difficulty: "hard", type: "practice"}] },
  { day: 100, phase: "Phase 5", topic: "Data Visualization", subtopics: [{title: "Basic plots (Matplotlib)", url: "https://www.youtube.com/results?search_query=Matplotlib+Tutorial", difficulty: "medium", type: "practice"}] },
  { day: 101, phase: "Phase 5", topic: "REVISION + PRACTICE", subtopics: [{title: "Work with a dataset (CSV)", url: "https://www.kaggle.com/datasets", difficulty: "hard", type: "project"}] },
  { day: 102, phase: "Phase 5", topic: "Data Preprocessing 🚨", subtopics: [{title: "Missing values & Handling nulls", url: "https://www.youtube.com/results?search_query=Machine+Learning+Data+Preprocessing", difficulty: "hard", type: "practice"}] },
  { day: 103, phase: "Phase 5", topic: "Encoding", subtopics: [{title: "Label encoding, One-hot encoding", url: "https://www.youtube.com/results?search_query=One+Hot+Encoding+Python", difficulty: "medium", type: "practice"}] },
  { day: 104, phase: "Phase 5", topic: "Feature Scaling", subtopics: [{title: "Normalization & Standardization", url: "https://www.youtube.com/results?search_query=Normalization+vs+Standardization+Machine+Learning", difficulty: "medium", type: "theory"}] },
  { day: 105, phase: "Phase 5", topic: "Train-Test Split", subtopics: [{title: "Splitting data & Avoid overfitting", url: "https://www.youtube.com/results?search_query=Train+Test+Split+Sklearn", difficulty: "easy", type: "practice"}] },
  { day: 106, phase: "Phase 5", topic: "ML Basics", subtopics: [{title: "Supervised vs Unsupervised learning", url: "https://www.youtube.com/results?search_query=Supervised+vs+Unsupervised+Learning", difficulty: "easy", type: "theory"}] },
  { day: 107, phase: "Phase 5", topic: "Linear Regression 🚨", subtopics: [{title: "Concept & Model training", url: "https://www.youtube.com/results?search_query=Linear+Regression+Python+Sklearn", difficulty: "hard", type: "practice"}] },
  { day: 108, phase: "Phase 5", topic: "Logistic Regression", subtopics: [{title: "Classification & Binary output", url: "https://www.youtube.com/results?search_query=Logistic+Regression+Python", difficulty: "hard", type: "practice"}] },
  { day: 109, phase: "Phase 5", topic: "Decision Trees", subtopics: [{title: "Tree structure & Interpretability", url: "https://www.youtube.com/results?search_query=Decision+Trees+Machine+Learning", difficulty: "medium", type: "practice"}] },
  { day: 110, phase: "Phase 5", topic: "Random Forest", subtopics: [{title: "Ensemble learning", url: "https://www.youtube.com/results?search_query=Random+Forest+Python", difficulty: "hard", type: "practice"}] },
  { day: 111, phase: "Phase 5", topic: "Model Evaluation 🚨", subtopics: [{title: "Accuracy, Precision, Recall, Matrix", url: "https://www.youtube.com/results?search_query=Machine+Learning+Evaluation+Metrics", difficulty: "hard", type: "theory"}] },
  { day: 112, phase: "Phase 5", topic: "Overfitting vs Underfitting", subtopics: [{title: "Model generalization", url: "https://www.youtube.com/results?search_query=Overfitting+vs+Underfitting", difficulty: "medium", type: "theory"}] },
  { day: 113, phase: "Phase 5", topic: "Model Improvement", subtopics: [{title: "Hyperparameters & Tuning basics", url: "https://www.youtube.com/results?search_query=Hyperparameter+Tuning+GridSearchCV", difficulty: "hard", type: "practice"}] },
  { day: 114, phase: "Phase 5", topic: "REVISION", subtopics: [{title: "Review ML algorithms", url: "https://github.com/", difficulty: "medium", type: "practice"}] },
  { day: 115, phase: "Phase 5", topic: "ML Project Planning", subtopics: [{title: "Decide Dataset", url: "https://www.kaggle.com/", difficulty: "medium", type: "project"}] },
  { day: 116, phase: "Phase 5", topic: "Build ML Project", subtopics: [{title: "Data cleaning", url: "https://github.com/", difficulty: "hard", type: "project"}] },
  { day: 117, phase: "Phase 5", topic: "Build ML Project", subtopics: [{title: "Model training", url: "https://github.com/", difficulty: "hard", type: "project"}] },
  { day: 118, phase: "Phase 5", topic: "Build ML Project", subtopics: [{title: "Evaluation", url: "https://github.com/", difficulty: "medium", type: "project"}] },
  { day: 119, phase: "Phase 5", topic: "Improve Project", subtopics: [{title: "Better metrics", url: "https://github.com/", difficulty: "hard", type: "project"}] },
  { day: 120, phase: "Phase 5", topic: "FINAL REVIEW 🚨", subtopics: [{title: "Explain model results", url: "https://github.com/", difficulty: "medium", type: "theory"}] },

  // --- PHASE 6: AI + BACKEND INTEGRATION ---
  { day: 121, phase: "Phase 6", topic: "ML Model Recap", subtopics: [{title: "Review Input/Output", url: "https://github.com/", difficulty: "easy", type: "theory"}] },
  { day: 122, phase: "Phase 6", topic: "Saving ML Models", subtopics: [{title: "Pickle / joblib", url: "https://www.youtube.com/results?search_query=Save+Machine+Learning+Model+Pickle", difficulty: "medium", type: "practice"}] },
  { day: 123, phase: "Phase 6", topic: "API Concept for ML", subtopics: [{title: "Request -> Prediction -> Response", url: "https://www.youtube.com/results?search_query=Machine+Learning+API+Concept", difficulty: "medium", type: "theory"}] },
  { day: 124, phase: "Phase 6", topic: "FastAPI Intro 🚨", subtopics: [{title: "What is FastAPI", url: "https://www.youtube.com/results?search_query=FastAPI+Tutorial", difficulty: "medium", type: "practice"}] },
  { day: 125, phase: "Phase 6", topic: "First ML API", subtopics: [{title: "Create endpoint", url: "https://www.youtube.com/results?search_query=FastAPI+Machine+Learning+Model", difficulty: "hard", type: "practice"}] },
  { day: 126, phase: "Phase 6", topic: "Input Handling", subtopics: [{title: "JSON input & validation", url: "https://fastapi.tiangolo.com/tutorial/body/", difficulty: "medium", type: "practice"}] },
  { day: 127, phase: "Phase 6", topic: "Error Handling in ML API", subtopics: [{title: "Invalid inputs", url: "https://fastapi.tiangolo.com/tutorial/handling-errors/", difficulty: "medium", type: "practice"}] },
  { day: 128, phase: "Phase 6", topic: "Testing ML API", subtopics: [{title: "Test endpoints via Postman", url: "https://www.youtube.com/results?search_query=Test+FastAPI+with+Postman", difficulty: "easy", type: "practice"}] },
  { day: 129, phase: "Phase 6", topic: "Performance Basics", subtopics: [{title: "Avoid reloading model", url: "https://fastapi.tiangolo.com/advanced/events/", difficulty: "medium", type: "theory"}] },
  { day: 130, phase: "Phase 6", topic: "Mini ML API Project", subtopics: [{title: "Build fully working ML API", url: "https://github.com/", difficulty: "hard", type: "project"}] },
  { day: 131, phase: "Phase 6", topic: "Java API Calls", subtopics: [{title: "HTTP clients in Java", url: "https://www.youtube.com/results?search_query=Java+HttpClient+Tutorial", difficulty: "hard", type: "practice"}] },
  { day: 132, phase: "Phase 6", topic: "JSON Parsing in Java", subtopics: [{title: "Convert JSON to Object (Jackson)", url: "https://www.youtube.com/results?search_query=Java+Jackson+JSON", difficulty: "medium", type: "practice"}] },
  { day: 133, phase: "Phase 6", topic: "Connect Java to ML API", subtopics: [{title: "Send request, Receive prediction", url: "https://github.com/", difficulty: "hard", type: "practice"}] },
  { day: 134, phase: "Phase 6", topic: "Data Flow Understanding", subtopics: [{title: "User -> Backend -> ML -> Response", url: "https://github.com/", difficulty: "medium", type: "theory"}] },
  { day: 135, phase: "Phase 6", topic: "Error Handling Across Systems", subtopics: [{title: "Fail-safe systems", url: "https://github.com/", difficulty: "hard", type: "practice"}] },
  { day: 136, phase: "Phase 6", topic: "Docker Intro 🚨", subtopics: [{title: "Docker & Containers", url: "https://www.youtube.com/results?search_query=Docker+Tutorial+for+Beginners", difficulty: "medium", type: "theory"}] },
  { day: 137, phase: "Phase 6", topic: "Dockerizing ML API", subtopics: [{title: "Dockerfile for Python", url: "https://fastapi.tiangolo.com/deployment/docker/", difficulty: "hard", type: "practice"}] },
  { day: 138, phase: "Phase 6", topic: "Dockerizing Java Backend", subtopics: [{title: "Container for Spring Boot", url: "https://spring.io/guides/gs/spring-boot-docker/", difficulty: "hard", type: "practice"}] },
  { day: 139, phase: "Phase 6", topic: "Running Multiple Services", subtopics: [{title: "Docker Compose", url: "https://www.youtube.com/results?search_query=Docker+Compose+Tutorial", difficulty: "hard", type: "practice"}] },
  { day: 140, phase: "Phase 6", topic: "REVISION + TESTING", subtopics: [{title: "Test Dockerized System", url: "https://github.com/", difficulty: "medium", type: "practice"}] },
  { day: 141, phase: "Phase 6", topic: "FINAL PROJECT PLANNING", subtopics: [{title: "Plan Features", url: "https://github.com/", difficulty: "hard", type: "project"}] },
  { day: 142, phase: "Phase 6", topic: "BUILD FINAL PROJECT", subtopics: [{title: "ML Model Setup", url: "https://github.com/", difficulty: "hard", type: "project"}] },
  { day: 143, phase: "Phase 6", topic: "BUILD FINAL PROJECT", subtopics: [{title: "Java Backend Setup", url: "https://github.com/", difficulty: "hard", type: "project"}] },
  { day: 144, phase: "Phase 6", topic: "BUILD FINAL PROJECT", subtopics: [{title: "API Integration", url: "https://github.com/", difficulty: "hard", type: "project"}] },
  { day: 145, phase: "Phase 6", topic: "BUILD FINAL PROJECT", subtopics: [{title: "Database Integration", url: "https://github.com/", difficulty: "hard", type: "project"}] },
  { day: 146, phase: "Phase 6", topic: "BUILD FINAL PROJECT", subtopics: [{title: "Dockerize System", url: "https://github.com/", difficulty: "hard", type: "project"}] },
  { day: 147, phase: "Phase 6", topic: "Improve Project", subtopics: [{title: "Add Error handling", url: "https://github.com/", difficulty: "medium", type: "project"}] },
  { day: 148, phase: "Phase 6", topic: "Performance Improvements", subtopics: [{title: "Faster responses", url: "https://github.com/", difficulty: "hard", type: "project"}] },
  { day: 149, phase: "Phase 6", topic: "Testing + Fixing", subtopics: [{title: "End-to-End Testing", url: "https://github.com/", difficulty: "hard", type: "project"}] },
  { day: 150, phase: "Phase 6", topic: "FINAL REVIEW", subtopics: [{title: "Explain Full system architecture", url: "https://github.com/", difficulty: "medium", type: "theory"}] },

  // --- PHASE 7: SYSTEM DESIGN ---
  { day: 151, phase: "Phase 7", topic: "What is System Design?", subtopics: [{title: "Components (client, server, DB)", url: "https://www.youtube.com/results?search_query=System+Design+Introduction", difficulty: "easy", type: "theory"}] },
  { day: 152, phase: "Phase 7", topic: "Scalability", subtopics: [{title: "Vertical vs Horizontal scaling", url: "https://www.youtube.com/results?search_query=Vertical+vs+Horizontal+Scaling", difficulty: "medium", type: "theory"}] },
  { day: 153, phase: "Phase 7", topic: "Load Balancing 🚨", subtopics: [{title: "Distribution of traffic", url: "https://www.youtube.com/results?search_query=What+is+Load+Balancing", difficulty: "medium", type: "theory"}] },
  { day: 154, phase: "Phase 7", topic: "Caching 🚨", subtopics: [{title: "Cache vs DB", url: "https://www.youtube.com/results?search_query=System+Design+Caching", difficulty: "medium", type: "theory"}] },
  { day: 155, phase: "Phase 7", topic: "Database Scaling", subtopics: [{title: "Read replicas & Sharding", url: "https://www.youtube.com/results?search_query=Database+Sharding", difficulty: "hard", type: "theory"}] },
  { day: 156, phase: "Phase 7", topic: "API Performance", subtopics: [{title: "Response optimization", url: "https://www.youtube.com/results?search_query=API+Performance+Optimization", difficulty: "medium", type: "theory"}] },
  { day: 157, phase: "Phase 7", topic: "Rate Limiting", subtopics: [{title: "Prevent abuse", url: "https://www.youtube.com/results?search_query=Rate+Limiting+System+Design", difficulty: "medium", type: "theory"}] },
  { day: 158, phase: "Phase 7", topic: "Logging & Monitoring 🚨", subtopics: [{title: "Logs & Metrics", url: "https://www.youtube.com/results?search_query=System+Design+Logging+and+Monitoring", difficulty: "medium", type: "theory"}] },
  { day: 159, phase: "Phase 7", topic: "Fault Tolerance", subtopics: [{title: "Handling failures", url: "https://www.youtube.com/results?search_query=System+Design+Fault+Tolerance", difficulty: "hard", type: "theory"}] },
  { day: 160, phase: "Phase 7", topic: "REVISION", subtopics: [{title: "Review System Design Concepts", url: "https://bytebytego.com/", difficulty: "medium", type: "theory"}] },
  { day: 161, phase: "Phase 7", topic: "Authentication Review", subtopics: [{title: "JWT recap", url: "https://github.com/", difficulty: "medium", type: "theory"}] },
  { day: 162, phase: "Phase 7", topic: "Authorization", subtopics: [{title: "Roles, Permissions", url: "https://github.com/", difficulty: "medium", type: "theory"}] },
  { day: 163, phase: "Phase 7", topic: "Secure APIs", subtopics: [{title: "Data validation", url: "https://github.com/", difficulty: "medium", type: "practice"}] },
  { day: 164, phase: "Phase 7", topic: "Microservices Intro", subtopics: [{title: "Monolith vs microservices", url: "https://www.youtube.com/results?search_query=Monolith+vs+Microservices", difficulty: "medium", type: "theory"}] },
  { day: 165, phase: "Phase 7", topic: "Service Communication", subtopics: [{title: "API-based communication", url: "https://www.youtube.com/results?search_query=Microservices+Communication", difficulty: "hard", type: "theory"}] },
  { day: 166, phase: "Phase 7", topic: "Message Queues", subtopics: [{title: "Async processing", url: "https://www.youtube.com/results?search_query=Message+Queues+Explained", difficulty: "hard", type: "theory"}] },
  { day: 167, phase: "Phase 7", topic: "Async Systems", subtopics: [{title: "Non-blocking operations", url: "https://github.com/", difficulty: "hard", type: "theory"}] },
  { day: 168, phase: "Phase 7", topic: "File Storage", subtopics: [{title: "Local vs cloud storage", url: "https://www.youtube.com/results?search_query=System+Design+File+Storage", difficulty: "medium", type: "theory"}] },
  { day: 169, phase: "Phase 7", topic: "Deployment Basics", subtopics: [{title: "Environments", url: "https://www.youtube.com/results?search_query=Software+Deployment+Process", difficulty: "easy", type: "theory"}] },
  { day: 170, phase: "Phase 7", topic: "Cloud Basics", subtopics: [{title: "AWS/GCP basics", url: "https://www.youtube.com/results?search_query=Cloud+Computing+Basics", difficulty: "medium", type: "theory"}] },
  { day: 171, phase: "Phase 7", topic: "FINAL PROJECT PLANNING", subtopics: [{title: "Plan Architecture", url: "https://github.com/", difficulty: "hard", type: "project"}] },
  { day: 172, phase: "Phase 7", topic: "BUILD FINAL SYSTEM", subtopics: [{title: "Develop AI Model Component", url: "https://github.com/", difficulty: "hard", type: "project"}] },
  { day: 173, phase: "Phase 7", topic: "BUILD FINAL SYSTEM", subtopics: [{title: "Develop Java Backend System", url: "https://github.com/", difficulty: "hard", type: "project"}] },
  { day: 174, phase: "Phase 7", topic: "BUILD FINAL SYSTEM", subtopics: [{title: "Implement Secure APIs", url: "https://github.com/", difficulty: "hard", type: "project"}] },
  { day: 175, phase: "Phase 7", topic: "BUILD FINAL SYSTEM", subtopics: [{title: "Implement Scalable DB", url: "https://github.com/", difficulty: "hard", type: "project"}] },
  { day: 176, phase: "Phase 7", topic: "BUILD FINAL SYSTEM", subtopics: [{title: "System Integration", url: "https://github.com/", difficulty: "hard", type: "project"}] },
  { day: 177, phase: "Phase 7", topic: "Optimize System", subtopics: [{title: "Add Caching", url: "https://github.com/", difficulty: "hard", type: "project"}] },
  { day: 178, phase: "Phase 7", topic: "Test System", subtopics: [{title: "Focus on Performance", url: "https://github.com/", difficulty: "hard", type: "project"}] },
  { day: 179, phase: "Phase 7", topic: "Debug + Improve", subtopics: [{title: "Final bug squashing", url: "https://github.com/", difficulty: "medium", type: "project"}] },
  { day: 180, phase: "Phase 7", topic: "FINAL REVIEW", subtopics: [{title: "Explain Architecture", url: "https://github.com/", difficulty: "medium", type: "theory"}] },

  // --- ELITE PHASE: DEEP LEARNING CORE ---
  { day: 181, phase: "Phase 8", topic: "What is Deep Learning?", subtopics: [{title: "Difference: ML vs DL", url: "https://www.youtube.com/results?search_query=What+is+Deep+Learning", difficulty: "easy", type: "theory"}] },
  { day: 182, phase: "Phase 8", topic: "Neuron & Layers", subtopics: [{title: "Input -> weights -> output math", url: "https://www.youtube.com/results?search_query=Artificial+Neuron+Explained", difficulty: "medium", type: "theory"}] },
  { day: 183, phase: "Phase 8", topic: "Activation Functions", subtopics: [{title: "ReLU, Sigmoid, Tanh", url: "https://www.youtube.com/results?search_query=Activation+Functions+Deep+Learning", difficulty: "medium", type: "theory"}] },
  { day: 184, phase: "Phase 8", topic: "Forward Propagation", subtopics: [{title: "Data flow through network", url: "https://www.youtube.com/results?search_query=Forward+Propagation+Neural+Networks", difficulty: "hard", type: "theory"}] },
  { day: 185, phase: "Phase 8", topic: "Loss Functions", subtopics: [{title: "MSE, Cross-entropy", url: "https://www.youtube.com/results?search_query=Loss+Functions+Deep+Learning", difficulty: "medium", type: "theory"}] },
  { day: 186, phase: "Phase 8", topic: "Gradient Descent 🚨", subtopics: [{title: "Learning rate & Optimization", url: "https://www.youtube.com/results?search_query=Gradient+Descent+Deep+Learning", difficulty: "hard", type: "theory"}] },
  { day: 187, phase: "Phase 8", topic: "Backpropagation 🚨", subtopics: [{title: "Chain rule & Updating weights", url: "https://www.youtube.com/results?search_query=Backpropagation+Explained", difficulty: "hard", type: "theory"}] },
  { day: 188, phase: "Phase 8", topic: "Overfitting in DL", subtopics: [{title: "Regularization & Dropout", url: "https://www.youtube.com/results?search_query=Regularization+and+Dropout+Deep+Learning", difficulty: "medium", type: "theory"}] },
  { day: 189, phase: "Phase 8", topic: "PyTorch Intro", subtopics: [{title: "Tensors & Basic operations", url: "https://www.youtube.com/results?search_query=PyTorch+Tutorial+for+Beginners", difficulty: "medium", type: "practice"}] },
  { day: 190, phase: "Phase 8", topic: "Model Building", subtopics: [{title: "Define model & Layers", url: "https://pytorch.org/tutorials/", difficulty: "hard", type: "practice"}] },
  { day: 191, phase: "Phase 8", topic: "Training Loop 🚨", subtopics: [{title: "Forward pass, Backward pass manually", url: "https://pytorch.org/tutorials/", difficulty: "hard", type: "practice"}] },
  { day: 192, phase: "Phase 8", topic: "Evaluation", subtopics: [{title: "Accuracy & Loss tracking", url: "https://pytorch.org/tutorials/", difficulty: "medium", type: "practice"}] },
  { day: 193, phase: "Phase 8", topic: "REVISION", subtopics: [{title: "Review PyTorch syntax", url: "https://github.com/", difficulty: "medium", type: "practice"}] },
  { day: 194, phase: "Phase 8", topic: "MINI DL PROJECT", subtopics: [{title: "Setup Data", url: "https://github.com/", difficulty: "medium", type: "project"}] },
  { day: 195, phase: "Phase 8", topic: "MINI DL PROJECT", subtopics: [{title: "Build Model", url: "https://github.com/", difficulty: "hard", type: "project"}] },
  { day: 196, phase: "Phase 8", topic: "MINI DL PROJECT", subtopics: [{title: "Write Training Loop", url: "https://github.com/", difficulty: "hard", type: "project"}] },
  { day: 197, phase: "Phase 8", topic: "MINI DL PROJECT", subtopics: [{title: "Train Model", url: "https://github.com/", difficulty: "hard", type: "project"}] },
  { day: 198, phase: "Phase 8", topic: "MINI DL PROJECT", subtopics: [{title: "Evaluation", url: "https://github.com/", difficulty: "medium", type: "project"}] },
  { day: 199, phase: "Phase 8", topic: "MINI DL PROJECT", subtopics: [{title: "Fixing issues", url: "https://github.com/", difficulty: "medium", type: "project"}] },
  { day: 200, phase: "Phase 8", topic: "MINI DL PROJECT", subtopics: [{title: "Finalize", url: "https://github.com/", difficulty: "medium", type: "project"}] },
  { day: 201, phase: "Phase 8", topic: "IMPROVE PROJECT", subtopics: [{title: "Better tuning", url: "https://github.com/", difficulty: "hard", type: "project"}] },
  { day: 202, phase: "Phase 8", topic: "IMPROVE PROJECT", subtopics: [{title: "Visualization", url: "https://github.com/", difficulty: "medium", type: "project"}] },
  { day: 203, phase: "Phase 8", topic: "IMPROVE PROJECT", subtopics: [{title: "Error analysis", url: "https://github.com/", difficulty: "hard", type: "project"}] },
  { day: 204, phase: "Phase 8", topic: "IMPROVE PROJECT", subtopics: [{title: "Refactor Model Code", url: "https://github.com/", difficulty: "hard", type: "project"}] },
  { day: 205, phase: "Phase 8", topic: "IMPROVE PROJECT", subtopics: [{title: "Hyperparameter tuning iteration 1", url: "https://github.com/", difficulty: "hard", type: "project"}] },
  { day: 206, phase: "Phase 8", topic: "IMPROVE PROJECT", subtopics: [{title: "Hyperparameter tuning iteration 2", url: "https://github.com/", difficulty: "hard", type: "project"}] },
  { day: 207, phase: "Phase 8", topic: "IMPROVE PROJECT", subtopics: [{title: "Document Architecture", url: "https://github.com/", difficulty: "medium", type: "project"}] },
  { day: 208, phase: "Phase 8", topic: "IMPROVE PROJECT", subtopics: [{title: "Exporting weights", url: "https://github.com/", difficulty: "medium", type: "project"}] },
  { day: 209, phase: "Phase 8", topic: "IMPROVE PROJECT", subtopics: [{title: "Testing exported model", url: "https://github.com/", difficulty: "medium", type: "project"}] },
  { day: 210, phase: "Phase 8", topic: "IMPROVE PROJECT", subtopics: [{title: "Final Push to GitHub", url: "https://github.com/", difficulty: "easy", type: "project"}] },

  // --- ELITE PHASE: CV + NLP ---
  { day: 211, phase: "Phase 9", topic: "CNN Basics 🚨", subtopics: [{title: "Convolution & Filters", url: "https://www.youtube.com/results?search_query=CNN+Convolution+and+Filters", difficulty: "hard", type: "theory"}] },
  { day: 212, phase: "Phase 9", topic: "CNN Layers", subtopics: [{title: "Pooling & Flattening", url: "https://www.youtube.com/results?search_query=CNN+Pooling+Layer", difficulty: "medium", type: "theory"}] },
  { day: 213, phase: "Phase 9", topic: "IMAGE PROJECT", subtopics: [{title: "Dataset Setup", url: "https://github.com/", difficulty: "medium", type: "project"}] },
  { day: 214, phase: "Phase 9", topic: "IMAGE PROJECT", subtopics: [{title: "Data Augmentation", url: "https://github.com/", difficulty: "hard", type: "project"}] },
  { day: 215, phase: "Phase 9", topic: "IMAGE PROJECT", subtopics: [{title: "CNN Architecture", url: "https://github.com/", difficulty: "hard", type: "project"}] },
  { day: 216, phase: "Phase 9", topic: "IMAGE PROJECT", subtopics: [{title: "Training", url: "https://github.com/", difficulty: "hard", type: "project"}] },
  { day: 217, phase: "Phase 9", topic: "IMAGE PROJECT", subtopics: [{title: "Evaluation", url: "https://github.com/", difficulty: "medium", type: "project"}] },
  { day: 218, phase: "Phase 9", topic: "IMAGE PROJECT", subtopics: [{title: "Tuning", url: "https://github.com/", difficulty: "hard", type: "project"}] },
  { day: 219, phase: "Phase 9", topic: "IMAGE PROJECT", subtopics: [{title: "Export", url: "https://github.com/", difficulty: "medium", type: "project"}] },
  { day: 220, phase: "Phase 9", topic: "IMAGE PROJECT", subtopics: [{title: "API Integration", url: "https://github.com/", difficulty: "hard", type: "project"}] },
  { day: 221, phase: "Phase 9", topic: "NLP Basics", subtopics: [{title: "Text preprocessing", url: "https://www.youtube.com/results?search_query=NLP+Text+Preprocessing", difficulty: "medium", type: "theory"}] },
  { day: 222, phase: "Phase 9", topic: "Tokenization", subtopics: [{title: "Word & Subword Tokenization", url: "https://www.youtube.com/results?search_query=NLP+Tokenization", difficulty: "medium", type: "theory"}] },
  { day: 223, phase: "Phase 9", topic: "Embeddings", subtopics: [{title: "Word2Vec, GloVe", url: "https://www.youtube.com/results?search_query=Word+Embeddings+NLP", difficulty: "hard", type: "theory"}] },
  { day: 224, phase: "Phase 9", topic: "NLP PROJECT", subtopics: [{title: "Dataset Setup", url: "https://github.com/", difficulty: "medium", type: "project"}] },
  { day: 225, phase: "Phase 9", topic: "NLP PROJECT", subtopics: [{title: "Preprocessing", url: "https://github.com/", difficulty: "hard", type: "project"}] },
  { day: 226, phase: "Phase 9", topic: "NLP PROJECT", subtopics: [{title: "Tokenization/Embedding", url: "https://github.com/", difficulty: "hard", type: "project"}] },
  { day: 227, phase: "Phase 9", topic: "NLP PROJECT", subtopics: [{title: "Model Base", url: "https://github.com/", difficulty: "hard", type: "project"}] },
  { day: 228, phase: "Phase 9", topic: "NLP PROJECT", subtopics: [{title: "Training", url: "https://github.com/", difficulty: "hard", type: "project"}] },
  { day: 229, phase: "Phase 9", topic: "NLP PROJECT", subtopics: [{title: "Evaluation", url: "https://github.com/", difficulty: "medium", type: "project"}] },
  { day: 230, phase: "Phase 9", topic: "NLP PROJECT", subtopics: [{title: "Finalize", url: "https://github.com/", difficulty: "medium", type: "project"}] },
  { day: 231, phase: "Phase 9", topic: "IMPROVE PROJECTS", subtopics: [{title: "Optimize CV API", url: "https://github.com/", difficulty: "hard", type: "project"}] },
  { day: 232, phase: "Phase 9", topic: "IMPROVE PROJECTS", subtopics: [{title: "Optimize NLP API", url: "https://github.com/", difficulty: "hard", type: "project"}] },
  { day: 233, phase: "Phase 9", topic: "IMPROVE PROJECTS", subtopics: [{title: "Integrate to Backend", url: "https://github.com/", difficulty: "hard", type: "project"}] },
  { day: 234, phase: "Phase 9", topic: "IMPROVE PROJECTS", subtopics: [{title: "Write Dockerfiles", url: "https://github.com/", difficulty: "medium", type: "project"}] },
  { day: 235, phase: "Phase 9", topic: "IMPROVE PROJECTS", subtopics: [{title: "Test Docker Compose", url: "https://github.com/", difficulty: "medium", type: "project"}] },
  { day: 236, phase: "Phase 9", topic: "IMPROVE PROJECTS", subtopics: [{title: "Handle concurrent inference", url: "https://github.com/", difficulty: "hard", type: "project"}] },
  { day: 237, phase: "Phase 9", topic: "IMPROVE PROJECTS", subtopics: [{title: "Add caching", url: "https://github.com/", difficulty: "hard", type: "project"}] },
  { day: 238, phase: "Phase 9", topic: "IMPROVE PROJECTS", subtopics: [{title: "Stress test models", url: "https://github.com/", difficulty: "hard", type: "project"}] },
  { day: 239, phase: "Phase 9", topic: "IMPROVE PROJECTS", subtopics: [{title: "Fix integration bugs", url: "https://github.com/", difficulty: "medium", type: "project"}] },
  { day: 240, phase: "Phase 9", topic: "IMPROVE PROJECTS", subtopics: [{title: "Final Review", url: "https://github.com/", difficulty: "easy", type: "project"}] },

  // --- ELITE PHASE: ADVANCED BACKEND + SYSTEMS ---
  { day: 241, phase: "Phase 10", topic: "Microservices Deep Dive", subtopics: [{title: "Decomposing Monolith Strategy", url: "https://microservices.io/", difficulty: "hard", type: "theory"}] },
  { day: 242, phase: "Phase 10", topic: "Microservices Deep Dive", subtopics: [{title: "API Gateways", url: "https://microservices.io/", difficulty: "hard", type: "theory"}] },
  { day: 243, phase: "Phase 10", topic: "Microservices Deep Dive", subtopics: [{title: "Service Discovery (Eureka)", url: "https://www.youtube.com/results?search_query=Spring+Boot+Eureka", difficulty: "hard", type: "practice"}] },
  { day: 244, phase: "Phase 10", topic: "Microservices Deep Dive", subtopics: [{title: "Inter-service Communication", url: "https://www.youtube.com/results?search_query=Spring+Boot+OpenFeign", difficulty: "hard", type: "practice"}] },
  { day: 245, phase: "Phase 10", topic: "Microservices Deep Dive", subtopics: [{title: "Circuit Breakers (Resilience4j)", url: "https://www.youtube.com/results?search_query=Spring+Boot+Resilience4j", difficulty: "hard", type: "practice"}] },
  { day: 246, phase: "Phase 10", topic: "Microservices Deep Dive", subtopics: [{title: "Distributed Tracing", url: "https://www.youtube.com/results?search_query=Spring+Boot+Distributed+Tracing", difficulty: "hard", type: "practice"}] },
  { day: 247, phase: "Phase 10", topic: "Messaging Queues", subtopics: [{title: "RabbitMQ Basics", url: "https://www.youtube.com/results?search_query=RabbitMQ+Tutorial", difficulty: "medium", type: "theory"}] },
  { day: 248, phase: "Phase 10", topic: "Messaging Queues", subtopics: [{title: "Spring Boot + RabbitMQ", url: "https://www.youtube.com/results?search_query=Spring+Boot+RabbitMQ", difficulty: "hard", type: "practice"}] },
  { day: 249, phase: "Phase 10", topic: "Messaging Queues", subtopics: [{title: "Kafka Concepts", url: "https://www.youtube.com/results?search_query=Apache+Kafka+Tutorial", difficulty: "hard", type: "theory"}] },
  { day: 250, phase: "Phase 10", topic: "Messaging Queues", subtopics: [{title: "Spring Boot + Kafka Integration", url: "https://www.youtube.com/results?search_query=Spring+Boot+Kafka", difficulty: "hard", type: "practice"}] },
  { day: 251, phase: "Phase 10", topic: "Messaging Queues", subtopics: [{title: "Event-Driven Architecture", url: "https://www.youtube.com/results?search_query=Event+Driven+Architecture", difficulty: "hard", type: "theory"}] },
  { day: 252, phase: "Phase 10", topic: "Advanced DB", subtopics: [{title: "Indexing Deep Dive (B-Trees)", url: "https://use-the-index-luke.com/", difficulty: "hard", type: "theory"}] },
  { day: 253, phase: "Phase 10", topic: "Advanced DB", subtopics: [{title: "ACID Properties & Transactions", url: "https://www.youtube.com/results?search_query=ACID+Properties+Database", difficulty: "medium", type: "theory"}] },
  { day: 254, phase: "Phase 10", topic: "Advanced DB", subtopics: [{title: "Isolation Levels", url: "https://www.youtube.com/results?search_query=Database+Isolation+Levels", difficulty: "hard", type: "theory"}] },
  { day: 255, phase: "Phase 10", topic: "Advanced DB", subtopics: [{title: "CQRS Pattern Intro", url: "https://microservices.io/patterns/data/cqrs.html", difficulty: "hard", type: "theory"}] },
  { day: 256, phase: "Phase 10", topic: "Advanced DB", subtopics: [{title: "Event Sourcing", url: "https://microservices.io/", difficulty: "hard", type: "theory"}] },
  { day: 257, phase: "Phase 10", topic: "Performance", subtopics: [{title: "Connection Pooling", url: "https://www.youtube.com/results?search_query=HikariCP+Spring+Boot", difficulty: "medium", type: "practice"}] },
  { day: 258, phase: "Phase 10", topic: "Performance", subtopics: [{title: "Redis Distributed Caching", url: "https://www.youtube.com/results?search_query=Redis+Distributed+Cache", difficulty: "hard", type: "practice"}] },
  { day: 259, phase: "Phase 10", topic: "Performance", subtopics: [{title: "JVM Tuning Basics", url: "https://www.youtube.com/results?search_query=JVM+Performance+Tuning", difficulty: "hard", type: "theory"}] },
  { day: 260, phase: "Phase 10", topic: "Performance", subtopics: [{title: "Profiling Java Apps", url: "https://www.youtube.com/results?search_query=Java+Profiling", difficulty: "hard", type: "practice"}] },
  { day: 261, phase: "Phase 10", topic: "Scalable Backend Project", subtopics: [{title: "Architecture Design", url: "https://github.com/", difficulty: "hard", type: "project"}] },
  { day: 262, phase: "Phase 10", topic: "Scalable Backend Project", subtopics: [{title: "Setup API Gateway", url: "https://github.com/", difficulty: "hard", type: "project"}] },
  { day: 263, phase: "Phase 10", topic: "Scalable Backend Project", subtopics: [{title: "Build User Microservice", url: "https://github.com/", difficulty: "hard", type: "project"}] },
  { day: 264, phase: "Phase 10", topic: "Scalable Backend Project", subtopics: [{title: "Build Core Microservice", url: "https://github.com/", difficulty: "hard", type: "project"}] },
  { day: 265, phase: "Phase 10", topic: "Scalable Backend Project", subtopics: [{title: "Integrate Kafka", url: "https://github.com/", difficulty: "hard", type: "project"}] },
  { day: 266, phase: "Phase 10", topic: "Scalable Backend Project", subtopics: [{title: "Implement Async Email", url: "https://github.com/", difficulty: "hard", type: "project"}] },
  { day: 267, phase: "Phase 10", topic: "Scalable Backend Project", subtopics: [{title: "Add Redis Caching", url: "https://github.com/", difficulty: "hard", type: "project"}] },
  { day: 268, phase: "Phase 10", topic: "Scalable Backend Project", subtopics: [{title: "Secure with JWT", url: "https://github.com/", difficulty: "hard", type: "project"}] },
  { day: 269, phase: "Phase 10", topic: "Scalable Backend Project", subtopics: [{title: "Setup Databases", url: "https://github.com/", difficulty: "hard", type: "project"}] },
  { day: 270, phase: "Phase 10", topic: "Scalable Backend Project", subtopics: [{title: "Dockerize services", url: "https://github.com/", difficulty: "hard", type: "project"}] },
  { day: 271, phase: "Phase 10", topic: "Scalable Backend Project", subtopics: [{title: "Write Docker Compose", url: "https://github.com/", difficulty: "hard", type: "project"}] },
  { day: 272, phase: "Phase 10", topic: "Scalable Backend Project", subtopics: [{title: "Test Inter-service comms", url: "https://github.com/", difficulty: "hard", type: "project"}] },
  { day: 273, phase: "Phase 10", topic: "Scalable Backend Project", subtopics: [{title: "Simulate failure", url: "https://github.com/", difficulty: "hard", type: "project"}] },
  { day: 274, phase: "Phase 10", topic: "Scalable Backend Project", subtopics: [{title: "Monitor with Zipkin", url: "https://github.com/", difficulty: "hard", type: "project"}] },
  { day: 275, phase: "Phase 10", topic: "Scalable Backend Project", subtopics: [{title: "Load Test with JMeter", url: "https://github.com/", difficulty: "hard", type: "project"}] },
  { day: 276, phase: "Phase 10", topic: "Scalable Backend Project", subtopics: [{title: "Fix bottlenecks", url: "https://github.com/", difficulty: "hard", type: "project"}] },
  { day: 277, phase: "Phase 10", topic: "Scalable Backend Project", subtopics: [{title: "Refactor DB Queries", url: "https://github.com/", difficulty: "hard", type: "project"}] },
  { day: 278, phase: "Phase 10", topic: "Scalable Backend Project", subtopics: [{title: "Implement proper pagination", url: "https://github.com/", difficulty: "hard", type: "project"}] },
  { day: 279, phase: "Phase 10", topic: "Scalable Backend Project", subtopics: [{title: "Final Code Cleanup", url: "https://github.com/", difficulty: "medium", type: "project"}] },
  { day: 280, phase: "Phase 10", topic: "Scalable Backend Project", subtopics: [{title: "Push to GitHub", url: "https://github.com/", difficulty: "easy", type: "project"}] },
  { day: 281, phase: "Phase 10", topic: "Kubernetes Basics", subtopics: [{title: "Intro to K8s (Pods, Nodes)", url: "https://www.youtube.com/results?search_query=Kubernetes+in+5+minutes", difficulty: "medium", type: "theory"}] },
  { day: 282, phase: "Phase 10", topic: "Kubernetes Basics", subtopics: [{title: "Deployments & Services", url: "https://www.youtube.com/results?search_query=Kubernetes+Deployments", difficulty: "hard", type: "theory"}] },
  { day: 283, phase: "Phase 10", topic: "Kubernetes Basics", subtopics: [{title: "Ingress Controllers", url: "https://www.youtube.com/results?search_query=Kubernetes+Ingress", difficulty: "hard", type: "theory"}] },
  { day: 284, phase: "Phase 10", topic: "Kubernetes Basics", subtopics: [{title: "Writing YAML configs", url: "https://kubernetes.io/", difficulty: "medium", type: "practice"}] },
  { day: 285, phase: "Phase 10", topic: "Kubernetes Integration", subtopics: [{title: "Deploy Project to Minikube", url: "https://github.com/", difficulty: "hard", type: "project"}] },
  { day: 286, phase: "Phase 10", topic: "Kubernetes Integration", subtopics: [{title: "Expose via Ingress", url: "https://github.com/", difficulty: "hard", type: "project"}] },
  { day: 287, phase: "Phase 10", topic: "Kubernetes Integration", subtopics: [{title: "Scale Pods & Test", url: "https://github.com/", difficulty: "hard", type: "project"}] },
  { day: 288, phase: "Phase 10", topic: "Cloud Deployment", subtopics: [{title: "AWS EC2 Setup", url: "https://www.youtube.com/results?search_query=AWS+EC2+Tutorial", difficulty: "medium", type: "practice"}] },
  { day: 289, phase: "Phase 10", topic: "Cloud Deployment", subtopics: [{title: "AWS RDS Setup", url: "https://www.youtube.com/results?search_query=AWS+RDS+Tutorial", difficulty: "medium", type: "practice"}] },
  { day: 290, phase: "Phase 10", topic: "Cloud Deployment", subtopics: [{title: "Deploy Docker to EC2", url: "https://www.youtube.com/results?search_query=Deploy+Docker+to+AWS+EC2", difficulty: "hard", type: "practice"}] },
  { day: 291, phase: "Phase 10", topic: "CI/CD Basics", subtopics: [{title: "GitHub Actions Intro", url: "https://www.youtube.com/results?search_query=GitHub+Actions+Tutorial", difficulty: "medium", type: "theory"}] },
  { day: 292, phase: "Phase 10", topic: "CI/CD Pipeline", subtopics: [{title: "Write build pipeline", url: "https://github.com/", difficulty: "hard", type: "practice"}] },
  { day: 293, phase: "Phase 10", topic: "CI/CD Pipeline", subtopics: [{title: "Automate Image push", url: "https://github.com/", difficulty: "hard", type: "practice"}] },
  { day: 294, phase: "Phase 10", topic: "Security", subtopics: [{title: "Env Variables Management", url: "https://www.youtube.com/results?search_query=Managing+Environment+Variables+Security", difficulty: "medium", type: "practice"}] },
  { day: 295, phase: "Phase 10", topic: "Security", subtopics: [{title: "HTTPS & SSL", url: "https://www.youtube.com/results?search_query=How+SSL+Works", difficulty: "medium", type: "theory"}] },
  { day: 296, phase: "Phase 10", topic: "System Design Practice", subtopics: [{title: "Design URL Shortener", url: "https://www.youtube.com/results?search_query=System+Design+URL+Shortener", difficulty: "hard", type: "practice"}] },
  { day: 297, phase: "Phase 10", topic: "System Design Practice", subtopics: [{title: "Design Chat System", url: "https://www.youtube.com/results?search_query=System+Design+Chat+Application", difficulty: "hard", type: "practice"}] },
  { day: 298, phase: "Phase 10", topic: "System Design Practice", subtopics: [{title: "Design Netflix", url: "https://www.youtube.com/results?search_query=System+Design+Netflix", difficulty: "hard", type: "practice"}] },
  { day: 299, phase: "Phase 10", topic: "System Design Practice", subtopics: [{title: "Design Uber/Ola", url: "https://www.youtube.com/results?search_query=System+Design+Uber", difficulty: "hard", type: "practice"}] },
  { day: 300, phase: "Phase 10", topic: "Final Architecture Review", subtopics: [{title: "Review all concepts", url: "https://bytebytego.com/", difficulty: "hard", type: "theory"}] },

  // --- ELITE PHASE: REAL AI ENGINEERING & MASTER PROJECT ---
  { day: 301, phase: "Phase 11", topic: "MLOps Intro", subtopics: [{title: "What is MLOps", url: "https://www.youtube.com/results?search_query=What+is+MLOps", difficulty: "medium", type: "theory"}] },
  { day: 302, phase: "Phase 11", topic: "Model Versioning", subtopics: [{title: "DVC (Data Version Control)", url: "https://www.youtube.com/results?search_query=DVC+Tutorial", difficulty: "hard", type: "practice"}] },
  { day: 303, phase: "Phase 11", topic: "Experiment Tracking", subtopics: [{title: "MLflow Basics", url: "https://www.youtube.com/results?search_query=MLflow+Tutorial", difficulty: "hard", type: "practice"}] },
  { day: 304, phase: "Phase 11", topic: "Automated Training", subtopics: [{title: "CI/CD for Machine Learning", url: "https://www.youtube.com/results?search_query=CI+CD+for+Machine+Learning", difficulty: "hard", type: "theory"}] },
  { day: 305, phase: "Phase 11", topic: "Monitoring", subtopics: [{title: "Data Drift", url: "https://www.youtube.com/results?search_query=Data+Drift+Machine+Learning", difficulty: "medium", type: "theory"}] },
  { day: 306, phase: "Phase 11", topic: "Monitoring", subtopics: [{title: "Model Decay Handling", url: "https://www.youtube.com/results?search_query=Handling+Model+Decay", difficulty: "medium", type: "theory"}] },
  { day: 307, phase: "Phase 11", topic: "LLM Integration", subtopics: [{title: "APIs Intro", url: "https://platform.openai.com/", difficulty: "easy", type: "theory"}] },
  { day: 308, phase: "Phase 11", topic: "LLM Integration", subtopics: [{title: "Prompt Engineering", url: "https://platform.openai.com/", difficulty: "medium", type: "practice"}] },
  { day: 309, phase: "Phase 11", topic: "LLM Integration", subtopics: [{title: "System Prompts", url: "https://platform.openai.com/", difficulty: "medium", type: "practice"}] },
  { day: 310, phase: "Phase 11", topic: "LLM Integration", subtopics: [{title: "Function Calling", url: "https://platform.openai.com/", difficulty: "hard", type: "practice"}] },
  { day: 311, phase: "Phase 11", topic: "Vector Databases", subtopics: [{title: "What are Vector DBs", url: "https://www.youtube.com/results?search_query=Vector+Databases+Explained", difficulty: "medium", type: "theory"}] },
  { day: 312, phase: "Phase 11", topic: "Vector Databases", subtopics: [{title: "Embeddings generation", url: "https://platform.openai.com/", difficulty: "hard", type: "practice"}] },
  { day: 313, phase: "Phase 11", topic: "RAG Architecture", subtopics: [{title: "Concept", url: "https://www.youtube.com/results?search_query=RAG+Architecture+Explained", difficulty: "hard", type: "theory"}] },
  { day: 314, phase: "Phase 11", topic: "RAG Implementation", subtopics: [{title: "Build pipeline in Python", url: "https://www.youtube.com/results?search_query=Build+RAG+Pipeline", difficulty: "hard", type: "practice"}] },
  { day: 315, phase: "Phase 11", topic: "AI Frameworks", subtopics: [{title: "LangChain Basics", url: "https://www.youtube.com/results?search_query=LangChain+Tutorial", difficulty: "hard", type: "practice"}] },
  { day: 316, phase: "Phase 11", topic: "AI Frameworks", subtopics: [{title: "LlamaIndex Basics", url: "https://www.youtube.com/results?search_query=LlamaIndex+Tutorial", difficulty: "hard", type: "practice"}] },
  { day: 317, phase: "Phase 11", topic: "AI SaaS Features", subtopics: [{title: "Smart Search APIs", url: "https://github.com/", difficulty: "hard", type: "practice"}] },
  { day: 318, phase: "Phase 11", topic: "AI SaaS Features", subtopics: [{title: "Contextual Chatbot logic", url: "https://github.com/", difficulty: "hard", type: "practice"}] },
  { day: 319, phase: "Phase 11", topic: "AI SaaS Features", subtopics: [{title: "Connecting Java to Vector DB", url: "https://github.com/", difficulty: "hard", type: "practice"}] },
  { day: 320, phase: "Phase 11", topic: "Cost Management", subtopics: [{title: "API Cost tracking", url: "https://platform.openai.com/", difficulty: "medium", type: "theory"}] },
  
  // FINAL MASTER PROJECT: AI SAAS PLATFORM (Days 321-365)
  { day: 321, phase: "FINAL MASTER PROJECT", topic: "AI SaaS Product", subtopics: [{title: "Define Scope", url: "https://github.com/", difficulty: "medium", type: "project"}] },
  { day: 322, phase: "FINAL MASTER PROJECT", topic: "AI SaaS Product", subtopics: [{title: "Architecture & DB Schema", url: "https://github.com/", difficulty: "hard", type: "project"}] },
  { day: 323, phase: "FINAL MASTER PROJECT", topic: "AI SaaS Product", subtopics: [{title: "Setup Java Backend Base", url: "https://github.com/", difficulty: "hard", type: "project"}] },
  { day: 324, phase: "FINAL MASTER PROJECT", topic: "AI SaaS Product", subtopics: [{title: "Setup Database", url: "https://github.com/", difficulty: "hard", type: "project"}] },
  { day: 325, phase: "FINAL MASTER PROJECT", topic: "AI SaaS Product", subtopics: [{title: "Implement Auth & Roles", url: "https://github.com/", difficulty: "hard", type: "project"}] },
  { day: 326, phase: "FINAL MASTER PROJECT", topic: "AI SaaS Product", subtopics: [{title: "User Management APIs", url: "https://github.com/", difficulty: "hard", type: "project"}] },
  { day: 327, phase: "FINAL MASTER PROJECT", topic: "AI SaaS Product", subtopics: [{title: "Setup FastAPI Service", url: "https://github.com/", difficulty: "hard", type: "project"}] },
  { day: 328, phase: "FINAL MASTER PROJECT", topic: "AI SaaS Product", subtopics: [{title: "Integrate ML into FastAPI", url: "https://github.com/", difficulty: "hard", type: "project"}] },
  { day: 329, phase: "FINAL MASTER PROJECT", topic: "AI SaaS Product", subtopics: [{title: "Setup Vector Database", url: "https://github.com/", difficulty: "hard", type: "project"}] },
  { day: 330, phase: "FINAL MASTER PROJECT", topic: "AI SaaS Product", subtopics: [{title: "Implement RAG Pipeline", url: "https://github.com/", difficulty: "hard", type: "project"}] },
  { day: 331, phase: "FINAL MASTER PROJECT", topic: "AI SaaS Product", subtopics: [{title: "Connect Java to FastAPI", url: "https://github.com/", difficulty: "hard", type: "project"}] },
  { day: 332, phase: "FINAL MASTER PROJECT", topic: "AI SaaS Product", subtopics: [{title: "Core Logic APIs (Part 1)", url: "https://github.com/", difficulty: "hard", type: "project"}] },
  { day: 333, phase: "FINAL MASTER PROJECT", topic: "AI SaaS Product", subtopics: [{title: "Core Logic APIs (Part 2)", url: "https://github.com/", difficulty: "hard", type: "project"}] },
  { day: 334, phase: "FINAL MASTER PROJECT", topic: "AI SaaS Product", subtopics: [{title: "File Uploads (AWS S3)", url: "https://github.com/", difficulty: "hard", type: "project"}] },
  { day: 335, phase: "FINAL MASTER PROJECT", topic: "AI SaaS Product", subtopics: [{title: "Async Tasks (Kafka)", url: "https://github.com/", difficulty: "hard", type: "project"}] },
  { day: 336, phase: "FINAL MASTER PROJECT", topic: "AI SaaS Product", subtopics: [{title: "Setup Webhooks", url: "https://github.com/", difficulty: "hard", type: "project"}] },
  { day: 337, phase: "FINAL MASTER PROJECT", topic: "AI SaaS Product", subtopics: [{title: "Caching for AI responses", url: "https://github.com/", difficulty: "hard", type: "project"}] },
  { day: 338, phase: "FINAL MASTER PROJECT", topic: "AI SaaS Product", subtopics: [{title: "Add Rate Limiting", url: "https://github.com/", difficulty: "hard", type: "project"}] },
  { day: 339, phase: "FINAL MASTER PROJECT", topic: "AI SaaS Product", subtopics: [{title: "Unit Tests for Backend", url: "https://github.com/", difficulty: "hard", type: "project"}] },
  { day: 340, phase: "FINAL MASTER PROJECT", topic: "AI SaaS Product", subtopics: [{title: "Tests for AI Service", url: "https://github.com/", difficulty: "hard", type: "project"}] },
  { day: 341, phase: "FINAL MASTER PROJECT", topic: "AI SaaS Product", subtopics: [{title: "Integration Testing", url: "https://github.com/", difficulty: "hard", type: "project"}] },
  { day: 342, phase: "FINAL MASTER PROJECT", topic: "AI SaaS Product", subtopics: [{title: "Error Logging", url: "https://github.com/", difficulty: "medium", type: "project"}] },
  { day: 343, phase: "FINAL MASTER PROJECT", topic: "AI SaaS Product", subtopics: [{title: "Dockerize Java App", url: "https://github.com/", difficulty: "hard", type: "project"}] },
  { day: 344, phase: "FINAL MASTER PROJECT", topic: "AI SaaS Product", subtopics: [{title: "Dockerize FastAPI", url: "https://github.com/", difficulty: "hard", type: "project"}] },
  { day: 345, phase: "FINAL MASTER PROJECT", topic: "AI SaaS Product", subtopics: [{title: "Write docker-compose.yml", url: "https://github.com/", difficulty: "hard", type: "project"}] },
  { day: 346, phase: "FINAL MASTER PROJECT", topic: "AI SaaS Product", subtopics: [{title: "Local Env Testing", url: "https://github.com/", difficulty: "medium", type: "project"}] },
  { day: 347, phase: "FINAL MASTER PROJECT", topic: "AI SaaS Product", subtopics: [{title: "Setup Cloud Provider", url: "https://github.com/", difficulty: "hard", type: "project"}] },
  { day: 348, phase: "FINAL MASTER PROJECT", topic: "AI SaaS Product", subtopics: [{title: "Provision Cloud DB", url: "https://github.com/", difficulty: "hard", type: "project"}] },
  { day: 349, phase: "FINAL MASTER PROJECT", topic: "AI SaaS Product", subtopics: [{title: "Deploy Microservices", url: "https://github.com/", difficulty: "hard", type: "project"}] },
  { day: 350, phase: "FINAL MASTER PROJECT", topic: "AI SaaS Product", subtopics: [{title: "Configure Domain, SSL", url: "https://github.com/", difficulty: "hard", type: "project"}] },
  { day: 351, phase: "FINAL MASTER PROJECT", topic: "AI SaaS Product", subtopics: [{title: "Setup CI/CD Actions", url: "https://github.com/", difficulty: "hard", type: "project"}] },
  { day: 352, phase: "FINAL MASTER PROJECT", topic: "AI SaaS Product", subtopics: [{title: "Load Testing", url: "https://github.com/", difficulty: "hard", type: "project"}] },
  { day: 353, phase: "FINAL MASTER PROJECT", topic: "AI SaaS Product", subtopics: [{title: "Query Optimization", url: "https://github.com/", difficulty: "hard", type: "project"}] },
  { day: 354, phase: "FINAL MASTER PROJECT", topic: "AI SaaS Product", subtopics: [{title: "Optimize Latency", url: "https://github.com/", difficulty: "hard", type: "project"}] },
  { day: 355, phase: "FINAL MASTER PROJECT", topic: "AI SaaS Product", subtopics: [{title: "Monitor Prod Logs", url: "https://github.com/", difficulty: "medium", type: "project"}] },
  { day: 356, phase: "FINAL MASTER PROJECT", topic: "AI SaaS Product", subtopics: [{title: "Security Audit", url: "https://github.com/", difficulty: "hard", type: "project"}] },
  { day: 357, phase: "FINAL MASTER PROJECT", topic: "AI SaaS Product", subtopics: [{title: "OpenAPI Documentation", url: "https://github.com/", difficulty: "medium", type: "project"}] },
  { day: 358, phase: "FINAL MASTER PROJECT", topic: "AI SaaS Product", subtopics: [{title: "Clean Up Code", url: "https://github.com/", difficulty: "medium", type: "project"}] },
  { day: 359, phase: "FINAL MASTER PROJECT", topic: "AI SaaS Product", subtopics: [{title: "Write README.md", url: "https://github.com/", difficulty: "medium", type: "project"}] },
  { day: 360, phase: "FINAL MASTER PROJECT", topic: "AI SaaS Product", subtopics: [{title: "Format GitHub Repo", url: "https://github.com/", difficulty: "medium", type: "project"}] },
  { day: 361, phase: "FINAL MASTER PROJECT", topic: "AI SaaS Product", subtopics: [{title: "Draft Architecture Diagrams", url: "https://github.com/", difficulty: "medium", type: "project"}] },
  { day: 362, phase: "FINAL MASTER PROJECT", topic: "AI SaaS Product", subtopics: [{title: "Prepare Presentation", url: "https://github.com/", difficulty: "medium", type: "project"}] },
  { day: 363, phase: "FINAL MASTER PROJECT", topic: "AI SaaS Product", subtopics: [{title: "Record Video", url: "https://github.com/", difficulty: "medium", type: "project"}] },
  { day: 364, phase: "FINAL MASTER PROJECT", topic: "AI SaaS Product", subtopics: [{title: "Edit Video", url: "https://github.com/", difficulty: "medium", type: "project"}] },
  { day: 365, phase: "FINAL MASTER PROJECT", topic: "GRADUATION", subtopics: [{title: "Update Resume & Apply!", url: "https://linkedin.com", difficulty: "easy", type: "theory"}] }
];

const foundationalPath = [
  // --- PART 1: MATHEMATICS FOR AI/ML (Days 1-30) ---
  { day: 1, phase: "Math", topic: "Vectors Basics", subtopics: [{title: "Vector addition & Scalar multiplication", url: "https://www.3blue1brown.com/topics/linear-algebra", difficulty: "easy", type: "theory"}] },
  { day: 2, phase: "Math", topic: "Dot & Cross Products", subtopics: [{title: "Geometric interpretation & Projections", url: "https://www.youtube.com/results?search_query=Dot+product+3blue1brown", difficulty: "medium", type: "theory"}] },
  { day: 3, phase: "Math", topic: "Matrices Basics", subtopics: [{title: "Matrix multiplication & Linear transformations", url: "https://www.youtube.com/results?search_query=Matrix+multiplication+linear+transformation", difficulty: "medium", type: "theory"}] },
  { day: 4, phase: "Math", topic: "Determinants & Inverses", subtopics: [{title: "Identity matrix, Singular matrices", url: "https://www.youtube.com/results?search_query=Determinant+of+a+matrix", difficulty: "medium", type: "theory"}] },
  { day: 5, phase: "Math", topic: "System of Linear Equations", subtopics: [{title: "Gaussian elimination", url: "https://www.youtube.com/results?search_query=Gaussian+elimination", difficulty: "hard", type: "practice"}] },
  { day: 6, phase: "Math", topic: "Eigenvalues & Eigenvectors", subtopics: [{title: "Concept & Calculation", url: "https://www.youtube.com/results?search_query=Eigenvectors+and+eigenvalues", difficulty: "hard", type: "theory"}] },
  { day: 7, phase: "Math", topic: "Principal Component Analysis (PCA)", subtopics: [{title: "Dimensionality reduction math", url: "https://www.youtube.com/results?search_query=PCA+mathematics", difficulty: "hard", type: "theory"}] },
  { day: 8, phase: "Math", topic: "Derivatives Basics", subtopics: [{title: "Power rule, Product rule, Quotient rule", url: "https://www.3blue1brown.com/topics/calculus", difficulty: "easy", type: "theory"}] },
  { day: 9, phase: "Math", topic: "The Chain Rule", subtopics: [{title: "Function composition derivatives", url: "https://www.youtube.com/results?search_query=Chain+rule+calculus", difficulty: "medium", type: "practice"}] },
  { day: 10, phase: "Math", topic: "Partial Derivatives", subtopics: [{title: "Multivariable calculus intro", url: "https://www.youtube.com/results?search_query=Partial+derivatives", difficulty: "medium", type: "theory"}] },
  { day: 11, phase: "Math", topic: "Gradients", subtopics: [{title: "Gradient vectors & Direction of steepest ascent", url: "https://www.youtube.com/results?search_query=Gradient+vector", difficulty: "hard", type: "theory"}] },
  { day: 12, phase: "Math", topic: "Gradient Descent Math", subtopics: [{title: "Step size & updating weights mathematically", url: "https://www.youtube.com/results?search_query=Gradient+descent+mathematics", difficulty: "hard", type: "practice"}] },
  { day: 13, phase: "Math", topic: "Jacobian & Hessian Matrices", subtopics: [{title: "Second-order derivatives in ML", url: "https://www.youtube.com/results?search_query=Hessian+matrix+machine+learning", difficulty: "hard", type: "theory"}] },
  { day: 14, phase: "Math", topic: "Backpropagation Math", subtopics: [{title: "Chain rule applied to Neural Networks", url: "https://www.youtube.com/results?search_query=Backpropagation+calculus", difficulty: "hard", type: "theory"}] },
  { day: 15, phase: "Math", topic: "Descriptive Statistics", subtopics: [{title: "Mean, Median, Mode, Variance, Std Dev", url: "https://www.youtube.com/results?search_query=Descriptive+statistics", difficulty: "easy", type: "theory"}] },
  { day: 16, phase: "Math", topic: "Probability Basics", subtopics: [{title: "Independent vs Dependent events", url: "https://www.youtube.com/results?search_query=Probability+basics", difficulty: "easy", type: "theory"}] },
  { day: 17, phase: "Math", topic: "Conditional Probability", subtopics: [{title: "P(A|B) calculations", url: "https://www.youtube.com/results?search_query=Conditional+probability", difficulty: "medium", type: "practice"}] },
  { day: 18, phase: "Math", topic: "Bayes' Theorem", subtopics: [{title: "Prior, Posterior, Likelihood", url: "https://www.youtube.com/results?search_query=Bayes+theorem", difficulty: "medium", type: "theory"}] },
  { day: 19, phase: "Math", topic: "Naive Bayes Math", subtopics: [{title: "Applying Bayes to classification", url: "https://www.youtube.com/results?search_query=Naive+Bayes+math", difficulty: "medium", type: "practice"}] },
  { day: 20, phase: "Math", topic: "Probability Distributions", subtopics: [{title: "Normal, Binomial, Poisson", url: "https://www.youtube.com/results?search_query=Probability+distributions", difficulty: "medium", type: "theory"}] },
  { day: 21, phase: "Math", topic: "PDFs & CDFs", subtopics: [{title: "Probability Density Functions", url: "https://www.youtube.com/results?search_query=PDF+vs+CDF", difficulty: "hard", type: "theory"}] },
  { day: 22, phase: "Math", topic: "Expected Value & Covariance", subtopics: [{title: "Correlation vs Covariance", url: "https://www.youtube.com/results?search_query=Covariance+and+correlation", difficulty: "medium", type: "theory"}] },
  { day: 23, phase: "Math", topic: "Hypothesis Testing", subtopics: [{title: "Null hypothesis, p-values", url: "https://www.youtube.com/results?search_query=Hypothesis+testing+p+value", difficulty: "hard", type: "theory"}] },
  { day: 24, phase: "Math", topic: "A/B Testing Math", subtopics: [{title: "Statistical significance", url: "https://www.youtube.com/results?search_query=A%2FB+testing+statistics", difficulty: "medium", type: "practice"}] },
  { day: 25, phase: "Math", topic: "NumPy Linear Algebra", subtopics: [{title: "np.dot, np.linalg.inv", url: "https://numpy.org/doc/stable/reference/routines.linalg.html", difficulty: "medium", type: "practice"}] },
  { day: 26, phase: "Math", topic: "Coding Gradient Descent", subtopics: [{title: "Implement GD from scratch in Python", url: "https://github.com/", difficulty: "hard", type: "project"}] },
  { day: 27, phase: "Math", topic: "Information Theory", subtopics: [{title: "Entropy & Cross-Entropy Loss", url: "https://www.youtube.com/results?search_query=Cross+entropy+loss+math", difficulty: "hard", type: "theory"}] },
  { day: 28, phase: "Math", topic: "Activation Functions Math", subtopics: [{title: "Sigmoid & Softmax equations", url: "https://www.youtube.com/results?search_query=Softmax+function+math", difficulty: "medium", type: "theory"}] },
  { day: 29, phase: "Math", topic: "Optimization Algorithms", subtopics: [{title: "Adam, RMSprop Math", url: "https://www.youtube.com/results?search_query=Adam+optimizer+math", difficulty: "hard", type: "theory"}] },
  { day: 30, phase: "Math", topic: "Final Math Review", subtopics: [{title: "Connect Math to ML Models", url: "https://github.com/", difficulty: "medium", type: "theory"}] },

  // --- PART 2: DATA STRUCTURES & ALGORITHMS (Days 31-90) ---
  { day: 31, phase: "DSA", topic: "Time & Space Complexity", subtopics: [{title: "Big O, Omega, Theta", url: "https://www.youtube.com/results?search_query=Big+O+notation", difficulty: "easy", type: "theory"}] },
  { day: 32, phase: "DSA", topic: "Arrays Deep Dive", subtopics: [{title: "Memory allocation & dynamic arrays", url: "https://www.youtube.com/results?search_query=Dynamic+arrays+memory", difficulty: "easy", type: "theory"}] },
  { day: 33, phase: "DSA", topic: "Two Pointers Pattern", subtopics: [{title: "Opposite ends & Same direction", url: "https://leetcode.com/tag/two-pointers/", difficulty: "medium", type: "practice"}] },
  { day: 34, phase: "DSA", topic: "Sliding Window Pattern", subtopics: [{title: "Fixed vs Dynamic windows", url: "https://leetcode.com/tag/sliding-window/", difficulty: "medium", type: "practice"}] },
  { day: 35, phase: "DSA", topic: "Prefix Sum", subtopics: [{title: "Range sum queries", url: "https://leetcode.com/tag/prefix-sum/", difficulty: "medium", type: "practice"}] },
  { day: 36, phase: "DSA", topic: "Binary Search Basics", subtopics: [{title: "Implementation & Mid-point overflow", url: "https://leetcode.com/problems/binary-search/", difficulty: "easy", type: "practice"}] },
  { day: 37, phase: "DSA", topic: "Advanced Binary Search", subtopics: [{title: "Search in rotated arrays", url: "https://leetcode.com/problems/search-in-rotated-sorted-array/", difficulty: "hard", type: "practice"}] },
  { day: 38, phase: "DSA", topic: "Sorting I", subtopics: [{title: "Bubble, Selection, Insertion Sort", url: "https://www.youtube.com/results?search_query=Sorting+algorithms", difficulty: "easy", type: "theory"}] },
  { day: 39, phase: "DSA", topic: "Sorting II", subtopics: [{title: "Merge Sort & Divide and Conquer", url: "https://www.youtube.com/results?search_query=Merge+sort", difficulty: "medium", type: "theory"}] },
  { day: 40, phase: "DSA", topic: "Sorting III", subtopics: [{title: "Quick Sort & Partitioning", url: "https://www.youtube.com/results?search_query=Quick+sort", difficulty: "medium", type: "practice"}] },
  { day: 41, phase: "DSA", topic: "Linked Lists Basics", subtopics: [{title: "Singly linked lists, traversal, reversal", url: "https://leetcode.com/problems/reverse-linked-list/", difficulty: "medium", type: "practice"}] },
  { day: 42, phase: "DSA", topic: "Fast & Slow Pointers", subtopics: [{title: "Cycle detection (Floyd's)", url: "https://leetcode.com/problems/linked-list-cycle/", difficulty: "medium", type: "practice"}] },
  { day: 43, phase: "DSA", topic: "Doubly Linked Lists", subtopics: [{title: "Insertion & Deletion", url: "https://www.youtube.com/results?search_query=Doubly+linked+list", difficulty: "medium", type: "practice"}] },
  { day: 44, phase: "DSA", topic: "Stacks", subtopics: [{title: "LIFO, Valid Parentheses", url: "https://leetcode.com/problems/valid-parentheses/", difficulty: "easy", type: "practice"}] },
  { day: 45, phase: "DSA", topic: "Monotonic Stacks", subtopics: [{title: "Next Greater Element", url: "https://leetcode.com/tag/monotonic-stack/", difficulty: "hard", type: "practice"}] },
  { day: 46, phase: "DSA", topic: "Queues", subtopics: [{title: "FIFO, Circular queues", url: "https://www.youtube.com/results?search_query=Queue+data+structure", difficulty: "easy", type: "practice"}] },
  { day: 47, phase: "DSA", topic: "Hash Maps & Sets", subtopics: [{title: "Collision handling, O(1) lookups", url: "https://leetcode.com/tag/hash-table/", difficulty: "easy", type: "practice"}] },
  { day: 48, phase: "DSA", topic: "Hashing Patterns", subtopics: [{title: "Two Sum, Frequency maps", url: "https://leetcode.com/problems/two-sum/", difficulty: "easy", type: "practice"}] },
  { day: 49, phase: "DSA", topic: "Strings Basics", subtopics: [{title: "Immutability & ASCII manipulation", url: "https://leetcode.com/tag/string/", difficulty: "easy", type: "practice"}] },
  { day: 50, phase: "DSA", topic: "Advanced Strings", subtopics: [{title: "Anagrams, Palindromes, Trie Basics", url: "https://leetcode.com/problems/valid-anagram/", difficulty: "medium", type: "practice"}] },
  { day: 51, phase: "DSA", topic: "Binary Trees Basics", subtopics: [{title: "Nodes, Depth, Height", url: "https://www.youtube.com/results?search_query=Binary+tree+basics", difficulty: "easy", type: "theory"}] },
  { day: 52, phase: "DSA", topic: "Tree Traversals", subtopics: [{title: "Inorder, Preorder, Postorder", url: "https://leetcode.com/problems/binary-tree-inorder-traversal/", difficulty: "medium", type: "practice"}] },
  { day: 53, phase: "DSA", topic: "Breadth-First Search (BFS)", subtopics: [{title: "Level order traversal using Queues", url: "https://leetcode.com/problems/binary-tree-level-order-traversal/", difficulty: "medium", type: "practice"}] },
  { day: 54, phase: "DSA", topic: "Depth-First Search (DFS)", subtopics: [{title: "Recursion in trees", url: "https://leetcode.com/problems/maximum-depth-of-binary-tree/", difficulty: "medium", type: "practice"}] },
  { day: 55, phase: "DSA", topic: "Binary Search Trees (BST)", subtopics: [{title: "Properties, Search, Insert", url: "https://leetcode.com/problems/search-in-a-binary-search-tree/", difficulty: "medium", type: "practice"}] },
  { day: 56, phase: "DSA", topic: "Lowest Common Ancestor", subtopics: [{title: "LCA in BST and Binary Trees", url: "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/", difficulty: "hard", type: "practice"}] },
  { day: 57, phase: "DSA", topic: "Heaps Basics", subtopics: [{title: "Min-Heap vs Max-Heap", url: "https://www.youtube.com/results?search_query=Heap+data+structure", difficulty: "medium", type: "theory"}] },
  { day: 58, phase: "DSA", topic: "Heapify & Priority Queues", subtopics: [{title: "Kth Largest Element", url: "https://leetcode.com/problems/kth-largest-element-in-an-array/", difficulty: "medium", type: "practice"}] },
  { day: 59, phase: "DSA", topic: "Top K Elements Pattern", subtopics: [{title: "Top K Frequent Elements", url: "https://leetcode.com/problems/top-k-frequent-elements/", difficulty: "medium", type: "practice"}] },
  { day: 60, phase: "DSA", topic: "Merge Intervals Pattern", subtopics: [{title: "Overlapping intervals", url: "https://leetcode.com/problems/merge-intervals/", difficulty: "medium", type: "practice"}] },
  { day: 61, phase: "DSA", topic: "Graph Representation", subtopics: [{title: "Adjacency Matrix vs List", url: "https://www.youtube.com/results?search_query=Graph+representation", difficulty: "easy", type: "theory"}] },
  { day: 62, phase: "DSA", topic: "Graph BFS", subtopics: [{title: "Shortest path in unweighted graphs", url: "https://leetcode.com/problems/rotting-oranges/", difficulty: "medium", type: "practice"}] },
  { day: 63, phase: "DSA", topic: "Graph DFS", subtopics: [{title: "Connected components, Number of Islands", url: "https://leetcode.com/problems/number-of-islands/", difficulty: "medium", type: "practice"}] },
  { day: 64, phase: "DSA", topic: "Topological Sort", subtopics: [{title: "Course Schedule", url: "https://leetcode.com/problems/course-schedule/", difficulty: "hard", type: "practice"}] },
  { day: 65, phase: "DSA", topic: "Dijkstra's Algorithm", subtopics: [{title: "Shortest path in weighted graphs", url: "https://www.youtube.com/results?search_query=Dijkstras+algorithm", difficulty: "hard", type: "theory"}] },
  { day: 66, phase: "DSA", topic: "Minimum Spanning Tree", subtopics: [{title: "Prim's & Kruskal's", url: "https://www.youtube.com/results?search_query=Minimum+spanning+tree", difficulty: "hard", type: "theory"}] },
  { day: 67, phase: "DSA", topic: "Disjoint Set (Union-Find)", subtopics: [{title: "Cycle detection in graphs", url: "https://leetcode.com/problems/redundant-connection/", difficulty: "hard", type: "practice"}] },
  { day: 68, phase: "DSA", topic: "Recursion Basics", subtopics: [{title: "Base cases & Call stack", url: "https://www.youtube.com/results?search_query=Recursion+explained", difficulty: "easy", type: "theory"}] },
  { day: 69, phase: "DSA", topic: "Backtracking Intro", subtopics: [{title: "Subsets, Permutations", url: "https://leetcode.com/problems/subsets/", difficulty: "medium", type: "practice"}] },
  { day: 70, phase: "DSA", topic: "Advanced Backtracking", subtopics: [{title: "N-Queens, Sudoku Solver", url: "https://leetcode.com/problems/n-queens/", difficulty: "hard", type: "practice"}] },
  { day: 71, phase: "DSA", topic: "DP Basics", subtopics: [{title: "Memoization vs Tabulation", url: "https://www.youtube.com/results?search_query=Dynamic+programming", difficulty: "medium", type: "theory"}] },
  { day: 72, phase: "DSA", topic: "1D DP - Fibonacci Style", subtopics: [{title: "Climbing Stairs, House Robber", url: "https://leetcode.com/problems/climbing-stairs/", difficulty: "easy", type: "practice"}] },
  { day: 73, phase: "DSA", topic: "1D DP - Longest Increasing Subsequence", subtopics: [{title: "LIS pattern", url: "https://leetcode.com/problems/longest-increasing-subsequence/", difficulty: "medium", type: "practice"}] },
  { day: 74, phase: "DSA", topic: "2D DP - Grid Traveler", subtopics: [{title: "Unique Paths", url: "https://leetcode.com/problems/unique-paths/", difficulty: "medium", type: "practice"}] },
  { day: 75, phase: "DSA", topic: "2D DP - Knapsack Problem", subtopics: [{title: "0/1 Knapsack basics", url: "https://www.youtube.com/results?search_query=0+1+knapsack", difficulty: "hard", type: "theory"}] },
  { day: 76, phase: "DSA", topic: "2D DP - Longest Common Subsequence", subtopics: [{title: "LCS implementation", url: "https://leetcode.com/problems/longest-common-subsequence/", difficulty: "hard", type: "practice"}] },
  { day: 77, phase: "DSA", topic: "Greedy Algorithms", subtopics: [{title: "Jump Game, Activity Selection", url: "https://leetcode.com/problems/jump-game/", difficulty: "medium", type: "practice"}] },
  { day: 78, phase: "DSA", topic: "Bit Manipulation", subtopics: [{title: "AND, OR, XOR, Shifts", url: "https://leetcode.com/problems/single-number/", difficulty: "easy", type: "practice"}] },
  { day: 79, phase: "DSA", topic: "Blind 75 - Arrays", subtopics: [{title: "Solve core array problems", url: "https://leetcode.com/discuss/general-discussion/460599/blind-75-leetcode-questions", difficulty: "medium", type: "practice"}] },
  { day: 80, phase: "DSA", topic: "Blind 75 - Strings", subtopics: [{title: "Solve core string problems", url: "https://leetcode.com/discuss/general-discussion/460599/blind-75-leetcode-questions", difficulty: "medium", type: "practice"}] },
  { day: 81, phase: "DSA", topic: "Blind 75 - Trees", subtopics: [{title: "Solve core tree problems", url: "https://leetcode.com/discuss/general-discussion/460599/blind-75-leetcode-questions", difficulty: "medium", type: "practice"}] },
  { day: 82, phase: "DSA", topic: "Blind 75 - Graphs", subtopics: [{title: "Solve core graph problems", url: "https://leetcode.com/discuss/general-discussion/460599/blind-75-leetcode-questions", difficulty: "hard", type: "practice"}] },
  { day: 83, phase: "DSA", topic: "Blind 75 - DP", subtopics: [{title: "Solve core DP problems", url: "https://leetcode.com/discuss/general-discussion/460599/blind-75-leetcode-questions", difficulty: "hard", type: "practice"}] },
  { day: 84, phase: "DSA", topic: "Mock Interview 1", subtopics: [{title: "Time yourself on 2 mediums", url: "https://pramp.com/", difficulty: "hard", type: "project"}] },
  { day: 85, phase: "DSA", topic: "Mock Interview 2", subtopics: [{title: "Time yourself on 1 hard", url: "https://pramp.com/", difficulty: "hard", type: "project"}] },
  { day: 86, phase: "DSA", topic: "Review Weak Areas", subtopics: [{title: "Revisit failed problems", url: "https://leetcode.com/", difficulty: "medium", type: "practice"}] },
  { day: 87, phase: "DSA", topic: "System Design vs DSA", subtopics: [{title: "Connecting structures to scaling", url: "https://github.com/", difficulty: "medium", type: "theory"}] },
  { day: 88, phase: "DSA", topic: "Competitive Programming Intro", subtopics: [{title: "Codeforces/CodeChef basics", url: "https://codeforces.com/", difficulty: "hard", type: "practice"}] },
  { day: 89, phase: "DSA", topic: "Final Grind", subtopics: [{title: "Solve 5 random mediums", url: "https://leetcode.com/problemset/all/", difficulty: "hard", type: "practice"}] },
  { day: 90, phase: "DSA", topic: "DSA Ready", subtopics: [{title: "Consistent daily problem solving from here", url: "https://leetcode.com/", difficulty: "easy", type: "theory"}] }
];
